hitobito/hitobito_sac_cas

CHANGELOG.md
app/domain/export/tabular/people/with_membership_number.rb
lib/hitobito_sac_cas/wagon.rb
spec/domain/export/tabular/people/with_membership_number_spec.rb

Add membership_number to tabular exports

---

README.md
app/models/group/geschaeftsstelle.rb
app/models/group/sektions_funktionaere.rb
app/models/group/sektions_tourenkommission.rb
config/locales/wagon.de.yml

Fixes #80
Abweichungen von https://saccas.atlassian.net/wiki/spaces/DIGISAC/pages/3869442236/Rollen-+Berechtigungskonzept:
Geschäftsstelle - Mitgliederdienst:
Schreibrechte auf Sektionen ist gekoppelt an Schreibrechte auf Sektions-Personen, -Kurse, -Touren, -Abos, Hütten etc.
Geschäftsstelle - Kursorganisation:
Schreibrechte nur auf die Kontaktdaten von Personen des Nationalverbands, nicht auf Personen der Sektionen.
In nationalen Kursen und Touren aber Schreibrecht auf die anlass-bezogenen Angaben (Anlassrolle, anlass-spezifische Fragen, Qualifikation)
Geschäftsstelle - Fundraising:
Vorerst nur Lesezugriff auf alle Personen, relevanter Schreibzugriff muss zusammen mit Opt-In Spendenaufrufe dazugebaut werden
Geschäftsstelle - Kommunikation:
Schreibrechte auf Abos des Nationalverbands sind …

Roles and permissions

---

db/seeds/self_registration_reasons.rb

Seed SelfRegistrationReason for SAC

---

CHANGELOG.md
app/controllers/people/neuanmeldungen/approves_controller.rb
app/controllers/people/neuanmeldungen/handler_controller.rb
app/controllers/people/neuanmeldungen/rejects_controller.rb
app/controllers/sac_cas/people_controller.rb
app/domain/people/neuanmeldungen/approve.rb
app/domain/people/neuanmeldungen/base.rb
app/domain/people/neuanmeldungen/reject.rb
app/views/people/neuanmeldungen/_actions_index.html.haml
app/views/people/neuanmeldungen/_multiselect_actions.html.haml
app/views/people/neuanmeldungen/handler/_fields.html.haml
app/views/people/neuanmeldungen/handler/_modal_form.html.haml
app/views/people/neuanmeldungen/handler/new.js.haml
app/views/people/neuanmeldungen/rejects/_fields.html.haml
config/locales/wagon.de.yml
config/routes.rb
db/seeds/development/0_groups.rb
db/seeds/development/1_people.rb
spec/controllers/people/neuanmeldungen/approves_controller_spec.rb
spec/controllers/people/neuanmeldungen/rejects_controller_spec.rb
spec/domain/people/neuanmeldungen/approve_spec.rb
spec/domain/people/neuanmeldungen/reject_spec.rb
spec/features/neuanmeldungen_approval_spec.rb

Neuanmeldungen verwalten

---

CHANGELOG.md
app/controllers/sac_cas/groups/self_inscription_controller.rb
app/models/sac_cas/person.rb
app/models/sac_cas/role_beitragskategorie.rb
app/views/groups/self_inscription/_details_sac.html.haml
config/locales/wagon.de.yml
db/seeds/development/0_groups.rb
lib/hitobito_sac_cas/wagon.rb
spec/features/login_spec.rb
spec/features/self_inscription_spec.rb
spec/features/self_registration_spec.rb
spec/fixtures/groups.yml

Allow login with membership number, customize self-inscription form

---

app/models/group/sektions_neuanmeldungen_sektion.rb
app/models/sac_cas/role/hard_destroy.rb
spec/models/group/sektions_neuanmeldungen_nv_spec.rb
spec/models/group/sektions_neuanmeldungen_sektion_spec.rb

Hard destroy neuanmeldung roles

---

config/settings.yml

Refs: https://github.com/hitobito/hitobito/issues/2259

Disable self service managed creation

---

app/models/sac_cas/self_registration.rb
app/models/sac_cas/self_registration/main_person.rb
spec/features/self_registration_spec.rb
spec/models/sac_cas/self_registration_spec.rb

fixes hitobito/hitobito_sac_cas#164

Adapt self registration for core changes, more specs

---

app/views/groups/self_registration/_household.html.haml
spec/features/self_registration_spec.rb

fixes hitobito/hitobito_sac_cas#166

Required attributes for housemates in self_registration

---

app/components/sac_cas/steps_component/content_component.rb
app/controllers/sac_cas/groups/self_registration_controller.rb
app/models/sac_cas/self_registration.rb
app/models/sac_cas/self_registration/main_person.rb
app/views/groups/self_registration/_main_email.html.haml
config/locales/wagon.de.yml
lib/hitobito_sac_cas/wagon.rb
spec/features/self_registration_spec.rb

Handle existing emails in self_registration via distinct step

---

app/models/sac_cas/self_registration/main_person.rb
app/views/groups/self_registration/_household.html.haml
spec/models/sac_cas/self_registration/main_person_spec.rb

Use Attributes API

---

spec/features/self_registration_spec.rb

fixes hitobito/hitobito_sac_cas#190

Add spec verifying address autocomplete in self_registration

---

app/domain/sac_cas/beitragskategorie/calculator.rb
app/models/sac_cas/future_role.rb
app/models/sac_cas/role_beitragskategorie.rb
spec/domain/sac_cas/beitragskategorie/calculator_spec.rb
spec/fabricators/role_fabricator.rb
spec/features/self_inscription_spec.rb
spec/models/future_role_spec.rb
spec/models/group/shared_examples_mitglied.rb
spec/models/group/shared_examples_neuanmeldung.rb
spec/models/person_spec.rb

Set/show beitragskategorie on FutureRole mitglied roles

---

app/views/roles/terminations/_additional_confirmation_text_sac.html.haml

Role terminations dialog: fix layout

---

app/views/people/_details_sac_cas.html.haml
spec/features/event_participation_spec.rb

Fix event participation show view, fixes #225

---

app/models/group/abo_basic_login.rb
app/models/group/abo_magazin.rb
app/models/group/abo_touren_portal.rb
app/models/group/abonnenten.rb
config/locales/wagon.de.yml
db/seeds/development/1_people.rb
db/seeds/groups.rb

Add abonnenten groups

---

app/domain/import/sektionen_importer.rb
app/models/group/ortsgruppe.rb
app/models/group/sektion.rb
config/locales/wagon.de.yml
spec/domain/import/sektionen_importer_spec.rb
spec/resources/sac_cas/group_resource_spec.rb

Add language as mounted attr for sektion and ortsgruppe

---

app/controllers/sac_cas/groups/self_inscription_controller.rb
app/models/self_inscription.rb
lib/hitobito_sac_cas/wagon.rb
spec/features/self_inscription_spec.rb
spec/features/self_registration_neuanmeldung_spec.rb
spec/models/self_inscription_spec.rb

Fix self_inscription, fixes #235

---

app/models/group/geschaeftsstelle.rb
config/locales/wagon.de.yml
db/seeds/development/1_people.rb
spec/controllers/people_controller_spec.rb
spec/features/self_inscription_spec.rb
spec/fixtures/roles.yml
spec/models/future_role_spec.rb
spec/models/role_spec.rb

fixes [#221](https://github.com/hitobito/hitobito_sac_cas/issues/221)

New roles for top layer Geschäftsstelle

---

spec/support/graphiti/schema.json

**!!! make sure to merge all PRs, or reopen ticket manually !!!**

Add graphiti schema, refs hitobito/hitobito#2345

---

app/components/sac_cas/steps_component.rb

Add responsiveness for self registration form

---

app/domain/sac_cas/roles/termination.rb
spec/domain/roles/termination_spec.rb

Fix termination for invalid roles

---

app/domain/sac_cas/people/sac_family.rb
app/domain/sac_cas/roles/termination.rb
app/models/group/abo_magazin.rb
app/models/group/abo_touren_portal.rb
app/models/sac_cas/person.rb
doc/README.md
spec/domain/roles/termination_spec.rb
spec/domain/sac_cas/people/sac_family_spec.rb
spec/fixtures/groups.yml
spec/fixtures/people.yml
spec/fixtures/roles.yml

Introduce domain class for sac family

---

app/domain/people/neuanmeldungen/promoter.rb
app/domain/people/neuanmeldungen/promoter/condition.rb
app/domain/people/neuanmeldungen/promoter/no_duplicate_condition.rb
app/domain/people/neuanmeldungen/promoter/paid_invoice_condition.rb
app/domain/people/neuanmeldungen/promoter/verified_email_condition.rb
app/jobs/promote_neuanmeldungen_job.rb
lib/hitobito_sac_cas/wagon.rb
spec/domain/people/neuanmeldungen/promoter/no_duplicate_condition_spec.rb
spec/domain/people/neuanmeldungen/promoter/paid_invoice_condition_spec.rb
spec/domain/people/neuanmeldungen/promoter/verified_email_condition_spec.rb
spec/domain/people/neuanmeldungen/promoter_spec.rb
spec/jobs/promote_neuanmeldungen_job_spec.rb

Implement Job that promotes Neuanmeldungen to Mitglieder, fixes #232

---

app/domain/groups/sektion_self_registration_link.rb
app/helpers/sac_cas/groups_helper.rb
app/models/group/ortsgruppe.rb
app/models/group/sektion.rb
app/models/group/sektions_neuanmeldungen_nv.rb
app/models/group/sektions_neuanmeldungen_sektion.rb
app/views/groups/_attrs_sac_cas.html.haml
config/locales/wagon.de.yml
spec/features/group_show_spec.rb
spec/features/self_registration_neuanmeldung_spec.rb
spec/models/group/ortsgruppe_spec.rb
spec/models/group/sektion_spec.rb
spec/models/group/sektions_neuanmeldungen_nv_spec.rb
spec/models/group/sektions_neuanmeldungen_sektion_spec.rb

Show sac neuanmeldungen self registration link on sektion

---

app/domain/people/neuanmeldungen/promoter.rb
spec/domain/people/neuanmeldungen/promoter_spec.rb

Prevent duplicate log entries in People::Neuanmeldungen::Promoter

---

app/models/self_registration_neuanmeldung.rb
spec/features/self_registration_neuanmeldung_spec.rb
spec/models/self_registration_neuanmeldung_spec.rb

Skip households in self reg if main_person is too young, refs #281

---

app/models/self_registration_neuanmeldung.rb
app/models/self_registration_neuanmeldung/housemate.rb
app/models/self_registration_neuanmeldung/main_person.rb
app/models/self_registration_neuanmeldung/supplements.rb
app/views/groups/self_registration/_agreement_link.html.haml
app/views/groups/self_registration/_supplements.html.haml
config/locales/wagon.de.yml
spec/features/self_registration_neuanmeldung_spec.rb
spec/models/self_registration_neuanmeldung/housemate_spec.rb
spec/models/self_registration_neuanmeldung/main_person_spec.rb
spec/models/self_registration_neuanmeldung/supplements_spec.rb
spec/models/self_registration_neuanmeldung_spec.rb

Enable section DSE for self reg neuanmeldung, refs #289

---

app/models/future_role/form_handling.rb
app/models/self_inscription.rb
app/models/self_registration_neuanmeldung/housemate.rb
app/models/self_registration_neuanmeldung/main_person.rb
app/models/self_registration_neuanmeldung/person.rb
app/views/groups/self_inscription/_form.html.haml
app/views/groups/self_registration/_supplements.html.haml
app/views/shared/_register_on_fields.html.haml
config/locales/wagon.de.yml
spec/features/self_inscription_spec.rb
spec/models/future_role/form_handling_spec.rb
spec/models/self_inscription_spec.rb
spec/views/shared/_register_on_fields.html.haml_spec.rb

Only render now and next register_on options, refs #295

---

app/models/sac_cas/self_registration.rb
app/models/self_registration_abo.rb
app/models/self_registration_abo/main_person.rb
app/views/groups/self_registration/_abo_infos.html.haml
app/views/groups/self_registration/_abo_issue.html.haml
app/views/groups/self_registration/_abo_main_person.html.haml
config/locales/wagon.de.yml
spec/features/self_registration_abo_spec.rb
spec/models/self_registration_abo/main_person_spec.rb
spec/models/self_registration_abo_spec.rb
spec/models/self_registration_neuanmeldung/main_person_spec.rb
spec/models/self_registration_spec.rb

Specify self registration for abos, refs #296

---

app/models/self_registration_neuanmeldung/main_person.rb
app/views/groups/self_registration/_supplements.html.haml
spec/features/self_registration_neuanmeldung_spec.rb
spec/features/self_registration_spec.rb
spec/models/self_registration/main_person_spec.rb
spec/models/self_registration_neuanmeldung/main_person_spec.rb

Add adult consent to both self reg forms, refs hitobito/hitobito#2404

---

spec/features/self_registration_neuanmeldung_spec.rb
spec/models/self_registration_neuanmeldung_spec.rb

Zusammen mit https://github.com/hitobito/hitobito/pull/2428 mergen

Spec out self reg stepping behaviour, refs #298

---

spec/models/self_registration_neuanmeldung/housemate_spec.rb

Spec that self reg housemate enqueues duplicate locator job,

---

app/domain/sac_cas/roles/termination.rb
app/views/roles/terminations/_additional_confirmation_text_sac.html.haml
app/views/roles/terminations/_role.html.haml
config/locales/wagon.de.yml
spec/domain/roles/termination_spec.rb
spec/features/roles/terminations_spec.rb

Improve UX of terminations dialog

---

app/models/self_registration/abo_basic_login/main_person.rb
app/models/self_registration/main_person/base.rb
spec/features/self_registration_abo_basic_login_spec.rb
spec/features/self_registration_abo_magazin_spec.rb
spec/features/self_registration_abo_touren_portal_spec.rb
spec/fixtures/mailing_lists.yml
spec/fixtures/mounted_attributes.yml
spec/fixtures/related_role_types.yml
spec/fixtures/subscriptions.yml

Selfreg: fix mailinglist subscribe/optout

---

spec/features/self_registration_abo_basic_login_spec.rb
spec/features/self_registration_abo_magazin_spec.rb
spec/features/self_registration_abo_touren_portal_spec.rb
spec/models/self_registration/abo_basic_login_spec.rb
spec/models/self_registration/abo_magazin_spec.rb
spec/models/self_registration/abo_touren_portal_spec.rb

Explicitly set self reg main_person for magazin and tourenportal

---

app/abilities/sac_cas/various_ability.rb
app/controllers/cost_centers_controller.rb
app/controllers/cost_units_controller.rb
app/helpers/sheet/cost_center.rb
app/helpers/sheet/cost_unit.rb
app/models/concerns/cost_common.rb
app/models/cost_center.rb
app/models/cost_unit.rb
app/views/cost_centers/_form.html.haml
app/views/cost_centers/_list.html.haml
app/views/cost_units/_form.html.haml
app/views/cost_units/_list.html.haml
app/views/shared/_admin_nav_kinds_nav_sac_cas.html.haml
config/locales/wagon.de.yml
config/routes.rb
db/migrate/20240308085009_add_cost_models.rb
lib/hitobito_sac_cas/wagon.rb
spec/abilities/various_ability_spec.rb
spec/fabricators/cost_common_fabricator.rb
spec/features/admin_cost_models_spec.rb
spec/models/concerns/cost_common_spec.rb

Add cost center and cost unit models, fixes #348

---

db/seeds/development/2_event_kinds_and_qualifications.rb

fixes #228 
Bin mir nicht ganz sicher, ob das so stimmt, inbesondere die `Event::KindQualificationKind` geschichte ..

Add event kind and qualification seeds, refs #228

---

app/components/sac_cas/steps_component.rb
app/domain/sac_cas/beitragskategorie/calculator.rb
app/models/self_registration/sektion/housemate.rb
config/locales/wagon.de.yml
spec/features/self_registration_sektion_spec.rb

Feature specs for selfreg

---

app/models/self_registration/base.rb
app/views/groups/self_registration/_form.html.haml
app/views/groups/self_registration/_main_email.html.haml
spec/features/self_registration_abo_basic_login_spec.rb
spec/features/self_registration_abo_magazin_spec.rb
spec/features/self_registration_abo_touren_portal_spec.rb
spec/features/self_registration_sektion_spec.rb
spec/features/self_registration_spec.rb
spec/models/self_registration/abo_basic_login_spec.rb
spec/models/self_registration/abo_magazin_spec.rb
spec/models/self_registration/abo_touren_portal_spec.rb
spec/models/self_registration/sektion_spec.rb

Selfreg: properly validate email on first step

---

app/models/sac_cas/person.rb

Depends on: https://github.com/hitobito/hitobito/pull/2457
Fixes: #274 
Successful CI run: https://github.com/hitobito/hitobito_sac_cas/actions/runs/8152041281

Remove english from person languages

---

CHANGELOG.md
app/decorators/sac_cas/role_decorator.rb
doc/oidc-claims.md
lib/hitobito_sac_cas/wagon.rb
spec/controllers/oauth/userinfo_controller_spec.rb
spec/requests/oauth_profile_spec.rb

**Merge hitobito/hitobito#2518 first!**
CI Test run with this PR and hitobito/hitobito#2518 together (the single test failure is also failing on master): https://github.com/hitobito/hitobito_sac_cas/actions/runs/8378750336/job/22944053088
Fixes #389

Add layer_group_id to with_roles claim

---

app/abilities/external_training_ability.rb
app/controllers/external_trainings_controller.rb
app/controllers/sac_cas/person/history_controller.rb
app/helpers/sheet/external_training.rb
app/models/external_training.rb
app/models/sac_cas/person.rb
app/views/external_trainings/_form.html.haml
app/views/person/history/_additional_information_sac_cas.html.haml
config/locales/wagon.de.yml
config/routes.rb
db/migrate/20240318080010_create_external_trainings.rb
lib/hitobito_sac_cas/wagon.rb
spec/abilities/external_training_ability_spec.rb
spec/fabricators/external_training_fabricator.rb
spec/features/external_training_model_spec.rb
spec/fixtures/event/kind_translations.yml
spec/models/external_training_spec.rb

Fixes: #261 
Requires: https://github.com/hitobito/hitobito/pull/2519
Successful CI run: https://github.com/hitobito/hitobito_sac_cas/actions/runs/8389015943

Add external training model

---

app/controllers/sac_cas/event/kinds_controller.rb
app/models/concerns/cost_common.rb
app/views/event/kinds/_fields_sac_cas.html.haml
app/views/event/kinds/_kind_category_field.html.haml
lib/hitobito_sac_cas/wagon.rb
spec/features/event/kinds_spec.rb
spec/fixtures/event/kind_category_translations.yml

Ich weise es dir zu weil jetzt anders als ticket spezifiziert ich das jetzt nicht via js sonder turbo frames umgesetzt habe, analog dem bei external trainings

Inherit selected fields from category on event/kind (#354)

---

app/models/sac_cas/event/course.rb
spec/models/event/course_spec.rb

Validate course attrs based on state, refs #230

---

app/jobs/event/close_applications_job.rb
app/models/sac_cas/event/course.rb
spec/fabricators/event_fabricator.rb
spec/fixtures/event/dates.yml
spec/fixtures/event_translations.yml
spec/fixtures/events.yml
spec/jobs/event/close_applications_job_spec.rb
spec/models/event/course_spec.rb

Es gibt noch ein problem mit den im youth wagon definierten state query methods, die bekommen die neuen possible_states nicht mit. Wie lösen wir das am besten?

WIP - Change course state depending on application_closing_at (#361)

---

app/controllers/sac_cas/event/kinds_controller.rb
app/models/sac_cas/event/course.rb
app/models/sac_cas/event/kind.rb
app/views/event/kinds/_actions_edit.html.haml
app/views/events/_fields_sac_cas.html.haml
config/locales/wagon.de.yml
config/routes.rb
db/migrate/20240403092333_add_unique_index_to_event_translations.rb
spec/controllers/event/kinds_controller_spec.rb
spec/models/event/kind_spec.rb

Analog MR aus #359, einzig die Translations machen einen unterschied. Was hältst du von der Anpassung der Tabelle damit wir das `upsert` machen können? Müssen wir das Thema bei der Vererbung via Formular auch noch irgendwie berücksichtigen oder informieren?

Add button to push inherited attrs from kind to course, (#360)

---

CHANGELOG.md
app/models/sac_cas/contactable.rb
lib/hitobito_sac_cas/wagon.rb
spec/models/person_spec.rb

Always print country for labels, fall back to switzerland

---

app/abilities/sac_cas/event/participation_ability.rb
app/controllers/sac_cas/event/kind_categories_controller.rb
app/controllers/sac_cas/event/participations_controller.rb
app/helpers/sac_cas/event/participation_buttons.rb
app/models/sac_cas/event/course.rb
app/models/sac_cas/event/participation.rb
config/locales/wagon.de.yml
config/routes.rb
db/migrate/20240404071312_add_previous_state_to_event_participations.rb
lib/hitobito_sac_cas/wagon.rb
spec/abilities/sac_cas/event/participation_ability_spec.rb
spec/controllers/event/participation_controller_spec.rb
spec/helpers/sac_cas/event/participation_buttons_spec.rb
spec/models/event/participation_spec.rb

Adjust course participation states, refs (#369)

---

app/helpers/sac_cas/filter_navigation/people.rb
config/locales/wagon.de.yml
spec/helpers/sac_cas/filter_navigation/people_spec.rb

erst nach #335 mergen und ggf noch den `role_kind` entsprechend anpassen.

Add default people filters for root and section (#336)

---

app/views/events/_attrs_application_sac_cas.html.haml
spec/fixtures/event/kind_translations.yml
spec/fixtures/event/kinds.yml

Ergänzung zu https://github.com/hitobito/hitobito_sac_cas/issues/353

Remove duplicate minimum age in course attrs

---

config/settings.yml

Specify participation cleanup settings, (#367)

---

app/helpers/sac_cas/events_helper.rb
app/models/sac_cas/event/course.rb
app/models/sac_cas/event/participatable.rb
app/views/cost_centers/_form.html.haml
app/views/cost_centers/_list.html.haml
app/views/cost_units/_form.html.haml
app/views/cost_units/_list.html.haml
app/views/events/_list_table.html.haml
config/locales/wagon.de.yml
db/migrate/20240410092526_add_unconfirmed_count_to_events.rb
lib/hitobito_sac_cas/wagon.rb
spec/controllers/events_controllers_spec.rb
spec/fixtures/event/dates.yml
spec/models/event/course_spec.rb

Mir ist noch nicht klar, was genau das Kriterium für unconfirmed ist.

Show unconfirmed participations on course list, (#373)

---

app/domain/sac_cas/person/household.rb
spec/features/person_edit_spec.rb

Person household: show validation error message

---

app/controllers/sac_cas/people_controller.rb
app/controllers/sac_cas/subscriptions_controller.rb
app/domain/export/tabular/people/sac_mitglieder.rb
app/domain/export/tabular/people/sac_recipient_row.rb
app/domain/export/tabular/people/sac_recipients.rb
app/domain/export/tabular/sac_group_people_base.rb
app/domain/import/sektionen_importer.rb
app/helpers/sac_cas/dropdown/people_export.rb
app/jobs/sac_cas/export/subscriptions_job.rb
app/models/sac_cas/group.rb
app/models/sac_cas/person.rb
config/initializers/inflections.rb
config/locales/wagon.de.yml
lib/hitobito_sac_cas/wagon.rb
spec/controllers/people_controller_spec.rb
spec/controllers/subscriptions_controller_spec.rb
spec/domain/export/tabular/people/sac_mitglieder_spec.rb
spec/domain/export/tabular/people/sac_recipient_row_spec.rb
spec/domain/export/tabular/people/sac_recipients_spec.rb
spec/features/people_export_spec.rb
spec/features/subscribers_export_spec.rb
spec/helpers/dropdown/people_export_spec.rb
spec/jobs/export/people_export_job_spec.rb
spec/jobs/export/subscriptions_job_spec.rb
spec/models/person_spec.rb

Implement receiver tabular export

---

app/views/event/kinds/_kind_category_field.html.haml
config/locales/wagon.de.yml

refs hitobito/hitobito_sac_cas#355

Add tooltip to kind_category inheritance link

---

config/locales/wagon.de.yml

Adjust course registration translations, refs: #250

---

app/views/groups/self_registration/_emailless_main_person.html.haml
app/views/groups/self_registration/_household.html.haml
app/views/groups/self_registration/_neuanmeldung_main_person.html.haml
config/locales/wagon.de.yml

Use example phonenumber placeholder in all selfreg forms, fixes #411

---

app/controllers/sac_cas/groups/self_inscription_controller.rb

Add missing unprocessable_entity status codes

---

app/domain/import/sektion/additional_membership.rb
app/domain/import/sektion/membership.rb
app/domain/people/sac_family.rb
app/helpers/sac_cas/people_helper.rb
app/models/sac_cas/role/mitglied_family_validations.rb
app/models/self_registration/main_person/base.rb
app/models/self_registration/sektion/main_person.rb
app/views/people/_details_sac_cas.html.haml
config/locales/wagon.de.yml
db/migrate/20240425155428_add_family_main_person_to_people.rb
db/seeds/development/support/sac_cas_person_seeder.rb
spec/controllers/people_controller_spec.rb
spec/domain/export/tabular/people/with_sac_additions_spec.rb
spec/domain/import/sektion/additional_membership_importer_spec.rb
spec/domain/import/sektion/membership_importer_spec.rb
spec/domain/import/sektion/membership_spec.rb
spec/domain/people/neuanmeldungen/approve_spec.rb
spec/domain/people/neuanmeldungen/promoter_spec.rb
spec/domain/people/neuanmeldungen/reject_spec.rb
spec/domain/people/sac_family_spec.rb
spec/domain/person/household_spec.rb
spec/features/person_edit_spec.rb
spec/fixtures/people.yml
spec/models/role_spec.rb
spec/models/self_registration/abo_basic_login/main_person_spec.rb
spec/models/self_registration/sektion/housemate_spec.rb
spec/models/self_registration/sektion/main_person_spec.rb
spec/views/people/_details_sac_cas.html.haml_spec.rb

Implement family main person flag, set during self-registration

---

app/decorators/sac_cas/person_decorator.rb
app/views/full_text/_people_columns_sac_cas.html.haml
lib/hitobito_sac_cas/wagon.rb
spec/decorators/person_decorator_spec.rb
spec/regressions/full_text_controller_spec.rb

Display member number in search results

---

app/helpers/sac_cas/filter_navigation/people.rb
config/locales/wagon.de.yml
spec/helpers/sac_cas/filter_navigation/people_spec.rb

Adjust preconfigured Tourenleiter filters, (#501)

---

app/abilities/sac_membership_config_ability.rb
app/components/sac_membership_configs/article_number_field_rows_component.rb
app/components/sac_membership_configs/field_rows_component.html.haml
app/components/sac_membership_configs/field_rows_component.rb
app/components/sac_membership_configs/valid_from_selector_component.html.haml
app/components/sac_membership_configs/valid_from_selector_component.rb
app/controllers/sac_membership_configs_controller.rb
app/decorators/sac_membership_config_decorator.rb
app/helpers/sac_cas/dropdown/group_edit.rb
app/helpers/sheet/sac_membership_config.rb
app/models/group/sac_cas.rb
app/models/sac_membership_config.rb
app/views/sac_membership_configs/_form.html.haml
config/locales/wagon.de.yml
config/routes.rb
db/migrate/20240502124158_create_sac_membership_configs.rb
db/seeds/development/3_sac_membership_configs.rb
lib/hitobito_sac_cas/wagon.rb
spec/controllers/sac_membership_configs_controller_spec.rb
spec/fixtures/sac_membership_configs.yml
spec/models/sac_membership_config_spec.rb

SAC membership configs

---

app/assets/stylesheets/hitobito/customizable/_wagon.scss
app/domain/export/pdf/passes/membership.rb
app/helpers/sac_cas/people_helper.rb
app/views/people/_show_right_z_sac_cas.html.haml
config/locales/wagon.de.yml
spec/views/people/_show_right_z_sac_cas.html.haml_spec.rb

#78
PDF Erstellungscode lasse ich absichtlich drin, da wir nun weiterhin mit prawn arbeiten. => #530

PEOPLE: QR Code Mitgliederausweis auf Profil

---

CHANGELOG.md
app/decorators/sac_cas/group_decorator.rb
spec/decorators/group_decorator_spec.rb

 ROLES: Sortierung der Rollentypen im Auswahlmenü #552 

---

app/controllers/sac_cas/person/query_household_controller.rb
lib/hitobito_sac_cas/wagon.rb
spec/controllers/person/query_household_controller_spec.rb

Refs: hitobito/hitobito_sac_cas#565

Adjust household people query matcher

---

app/abilities/sac_cas/person_ability.rb
app/controllers/people/sac_family_main_person_controller.rb
app/domain/people/sac_family.rb
app/helpers/sac_cas/people_helper.rb
config/routes.rb
spec/abilities/sac_cas/ability_spec.rb
spec/abilities/sac_cas/person_ability_spec.rb
spec/controllers/people/sac_family_main_person_controller_spec.rb
spec/views/people/_details_sac_cas.html.haml_spec.rb

2024/05/31 Bitte reviewen, nachdem checks durchgelaufen sind. :)

PEOPLE: Controller zum Ändern der family main person (#555)

---

app/helpers/sac_cas/event/participation_banner.rb
config/locales/wagon.de.yml
db/seeds/development/1_people.rb
db/seeds/development/events.rb
db/seeds/development/support/sac_event_seeder.rb
db/seeds/development/support/sac_person_seeder.rb
spec/helpers/sac_cas/event/participation_banner_spec.rb

EVENTS: Anmeldebanner je nach TN Status

---

app/controllers/sac_cas/person/query_household_controller.rb

Remove query_household_controller scope customization

---

app/components/sac_cas/household_aside_member_component.rb
lib/hitobito_sac_cas/wagon.rb
spec/components/sac_cas/household_aside_member_component_spec.rb

override household aside to show age in sac wagon. (hitobito#2622)

---

app/models/sac_cas/event/course.rb
spec/controllers/event/application_market_controller_spec.rb
spec/controllers/event/participations_controller_spec.rb

Add summoned to participation states

---

app/components/sac_cas/household_aside_component.rb
app/components/sac_cas/household_aside_member_component.rb
config/locales/wagon.de.yml
lib/hitobito_sac_cas/wagon.rb
spec/components/sac_cas/household_aside_component_spec.rb
spec/components/sac_cas/household_aside_member_component_spec.rb
spec/features/person_edit_spec.rb
spec/regressions/households_controller_spec.rb

fixes #550 PEOPLE household management view SAC Anpassungen

PEOPLE: household management view SAC Anpassungen (#550)

---

app/domain/sac_cas/beitragskategorie/calculator.rb
app/models/sac_cas/person.rb
spec/domain/sac_cas/beitragskategorie/calculator_spec.rb

PEOPLE: Beitragskategorie reference date #655

---

app/models/wizards/steps/membership_terminated_info.rb
app/views/wizards/steps/_membership_terminated_info.html.haml
config/locales/wagon.de.yml
spec/components/previews/wizards_preview.rb
spec/models/wizards/steps/membership_terminated_info_spec.rb
spec/views/wizards/steps/_membership_terminated_info.html.haml_spec.rb

Add membership terminated info wizard step (#653)

---

app/views/cost_centers/_attrs.html.haml
app/views/cost_units/_attrs.html.haml
config/locales/wagon.de.yml
config/routes.rb

Refs: hitobito/hitobito_sac_cas#537

Add view routes and templates for cost_unit and cost_center

---

app/controllers/sac_cas/qualifications_controller.rb
app/models/sac_cas/qualification.rb
config/locales/wagon.de.yml
spec/controllers/qualifications_controller_spec.rb
spec/models/qualification_spec.rb

EVENTS: Qualifikationen nicht in der Zukunft erfassbar

---

app/abilities/termination_reason_ability.rb
app/controllers/termination_reasons_controller.rb
app/helpers/sheet/termination_reason.rb
app/models/sac_cas/role.rb
app/models/termination_reason.rb
app/views/shared/_admin_nav_main_sac_cas.html.haml
app/views/termination_reasons/_form.html.haml
app/views/termination_reasons/_list.html.haml
config/locales/models.de.yml
config/locales/wagon.de.yml
config/routes.rb
db/migrate/20240701064324_create_termination_reasons.rb
lib/hitobito_sac_cas/wagon.rb
spec/abilities/termination_reason_ability_spec.rb
spec/controllers/termination_reasons_controller_spec.rb
spec/fabricators/termination_reason_fabricator.rb
spec/models/role_spec.rb

Add TerminationReasons (#647)

---

app/models/sac_cas/event/course.rb
db/migrate/20240701083828_add_class_size_and_age_to_event_kinds.rb
spec/models/event/course_spec.rb

EVENTS: Modellanpassungen Kurs/Kursart

---

app/models/external_training.rb
spec/models/external_training_spec.rb

Refs: hitobito/hitobito_sac_cas#538

Validate external trainings to not have finish_at in future

---

app/models/sac_cas/event/kind.rb

Re-add lost presence validations after rubocop autoformat

---

app/models/concerns/capitalized_dependent_errors.rb
app/models/concerns/cost_common.rb
app/models/course_compensation_category.rb
app/models/course_compensation_rate.rb
config/locales/wagon.de.yml
db/migrate/20240702081323_create_course_compensation_models.rb
spec/fabricators/course_compensation_category_fabricator.rb
spec/fabricators/course_compensation_rate_fabricator.rb
spec/models/course_compensation_category_spec.rb
spec/models/course_compensation_rate_spec.rb

Add course compensation models

---

app/domain/export/tabular/people/sac_mitglied_row.rb
app/views/groups/_actions_show_sac_cas.html.haml
spec/domain/export/tabular/people/sac_mitglied_row_spec.rb

PEOPLE: Bemerkungsfelder in Mitglieder-Adressen-Export

---

app/models/memberships/leave_zusatzsektion.rb
app/models/wizards/memberships/leave_zusatzsektion.rb
spec/features/memberships/leave_zusatzsektion_spec.rb
spec/models/memberships/leave_zusatzsektion_spec.rb

Store termination reasons in austritt zusatzsektion wizard

---

app/domain/table_displays/resolver.rb
app/domain/table_displays/resolving_column.rb
app/helpers/sac_cas/dropdown/table_displays.rb
lib/hitobito_sac_cas/wagon.rb
spec/domain/table_displays/resolver_spec.rb
spec/domain/table_displays/resolving_column_spec.rb
spec/features/people_controller_spec.rb

Fixes #515
Fügt Felder zu `Personen > Spalten` hinzu

 PEOPLE: Bemerkungsfelder in TableDisplay

---

app/controllers/people/neuanmeldungen/handler_controller.rb
app/domain/people/neuanmeldungen/base.rb
app/views/people/neuanmeldungen/handler/_modal_form.html.haml
config/locales/wagon.de.yml
spec/controllers/people/neuanmeldungen/approves_controller_spec.rb
spec/controllers/people/neuanmeldungen/rejects_controller_spec.rb
spec/features/neuanmeldungen_approval_spec.rb

 PEOPLE: Neuanmeldungen - alle Familien-Mitglieder gleichzeitig annehmen/ablehnen

---

app/mailers/memberships/leave_zusatzsektion_mailer.rb
app/models/wizards/memberships/leave_zusatzsektion.rb
db/seeds/custom_contents.rb
spec/features/memberships/leave_zusatzsektion_spec.rb
spec/mailers/memberships/leave_zusatzsektion_mailer_spec.rb

Send confirmation email when leaving zusatzsektion

---

app/abilities/sac_cas/event/participation_ability.rb
app/controllers/sac_cas/event/participations_controller.rb
app/models/sac_cas/event.rb
app/models/sac_cas/event/participation.rb
app/views/event/participations/_answers_step.html.haml
app/views/event/participations/_application_details.html.haml
app/views/event/participations/_fields_sac_cas.html.haml
config/locales/wagon.de.yml
db/migrate/20240705084928_add_actual_days_to_event_participations.rb
spec/abilities/sac_cas/event/participation_ability_spec.rb
spec/controllers/event/participations_controller_spec.rb
spec/models/event/participation_spec.rb

Refs: hitobito/hitobito_sac_cas#670

Allow event leaders to edit actual days for participations

---

app/jobs/event/leader_reminder_job.rb
app/mailers/event/leader_reminder_mailer.rb
db/seeds/custom_contents.rb
spec/jobs/event/leader_reminder_job_spec.rb

EVENTS: E-Mail Reminder Kursvorbereitungen

---

app/jobs/event/published_job.rb
app/mailers/event/published_mailer.rb
app/models/sac_cas/event/course.rb
db/seeds/custom_contents.rb
spec/models/event/course_spec.rb

EVENTS: E-Mail Kursveröffentlichung

---

app/abilities/sac_cas/various_ability.rb
lib/hitobito_sac_cas/wagon.rb
spec/abilities/sac_cas/various_ability_spec.rb
spec/fixtures/hitobito_log_entries.yml

permission hitobito log

---

app/jobs/event/application_paused_job.rb
app/mailers/concerns/event_mailer.rb
app/mailers/event/application_paused_mailer.rb
app/mailers/event/leader_reminder_mailer.rb
app/mailers/event/published_mailer.rb
app/models/sac_cas/event/course.rb
db/seeds/custom_contents.rb
spec/models/event/course_spec.rb

EVENTS: E-Mail Anmeldung pausiert

---

app/mailers/event/published_mailer.rb
spec/models/event/course_spec.rb

Fixes #599
send mail to course leaders instead of contact

EVENTS: E-Mail Kursveröffentlichung fix

---

app/mailers/sac_cas/event/participation_mailer.rb
app/models/concerns/events/courses/state.rb
db/seeds/custom_contents.rb
spec/mailers/participation_mailer_spec.rb
spec/models/event/course_spec.rb

Events: E-Mail Aufgebot (#633)

---

app/mailers/sac_cas/application_mailer.rb
spec/models/event/course_spec.rb

Refs #600
hat im sac_cas mailer noch gefehlt

MAIL: Localize sender name

---

spec/resources/group/reads_spec.rb

by using draper with helpers the request environment will be there.

Fix flaky resources/group/reads_spec (#821)

---

app/models/person/data_quality_issue.rb
app/models/sac_cas/person.rb
config/locales/wagon.de.yml
db/migrate/20240813072058_create_person_data_quality_issues.rb
spec/fabricators/person_data_quality_issue_fabricator.rb
spec/fabricators/person_fabricator.rb
spec/models/person/data_quality_issue_spec.rb
spec/models/person_spec.rb

PEOPLE: Datenqualität

---

app/models/wizards/memberships/terminate_sac_membership_wizard.rb
spec/features/memberships/sac_terminate_membership_wizard_spec.rb

PEOPLE: Wizard SAC Austritt termination_by_section_only check erweitern

---

app/abilities/json_api/external_invoice_ability.rb
app/abilities/sac_cas/token_ability.rb
app/controllers/json_api/external_invoices_controller.rb
app/models/external_invoice.rb
app/resources/external_invoice_resource.rb
config/routes.rb
db/migrate/20240809145808_add_external_invoices_to_service_tokens.rb
lib/hitobito_sac_cas/wagon.rb
spec/abilities/external_invoice_ability_spec.rb
spec/abilities/json_api/external_invoice_ability_spec.rb
spec/abilities/token_ability_spec.rb
spec/api/external_invoices/index_spec.rb
spec/api/external_invoices/show_spec.rb
spec/api/external_invoices/update_spec.rb
spec/fixtures/service_tokens.yml
spec/resources/external_invoice/reads_spec.rb
spec/resources/external_invoice/writes_spec.rb
spec/support/graphiti/schema.json

Bitte vor dem mergen tokenability reviewen. (In Spec funktioniert Token z.b. nicht für Mitglied)

INVOICES: External Invoices API (#736)

---

app/models/sac_cas/person.rb
spec/fabricators/person_fabricator.rb
spec/models/person_spec.rb

use actual enum instead of faking it

PEOPLE: Data quality enum

---

app/helpers/sac_cas/people_helper.rb
app/views/people/_data_quality_sac_cas.html.haml
spec/features/people/show_spec.rb

PEOPLE: Data quality on `Person#show`

---

app/domain/sac_imports/callback_blacklist.rb
app/jobs/people/data_quality_checker_job.rb
spec/jobs/people/data_quality_checker_job_spec.rb

PEOPLE: Initial data quality check

---

app/models/group/sac_cas.rb
app/models/group/sac_cas_verbaende.rb
app/models/group/sac_cas_verband.rb
config/locales/wagon.de.yml

Add associations and organisations groups

---

.github/workflows/tests.yml

create pr to build other branches

Run github action only when pushing master branch

---

app/controllers/people/membership_invoices_controller.rb
app/jobs/invoices/abacus/create_invoice_job.rb
app/models/external_invoice/sac_membership.rb
app/models/people/membership/invoice_form.rb
app/views/people/membership_invoices/new.html.haml
config/locales/wagon.de.yml
spec/controllers/people/membership_invoices_controller_spec.rb
spec/features/people/invoices_spec.rb
spec/jobs/invoices/abacus/create_invoice_job_spec.rb

Create invoice only if no data quality errors exist

---

app/domain/invoices/sac_memberships/extend_roles_for_invoicing.rb
app/jobs/invoices/abacus/create_yearly_invoices_job.rb
spec/domain/invoices/sac_memberships/extend_roles_for_invoicing_spec.rb

Extend yearly membership invoice roles

---

app/abilities/sac_cas/group_ability.rb
app/controllers/people/yearly_membership_invoices_controller.rb
app/helpers/sheet/people/yearly_membership_invoice.rb
app/models/people/yearly_membership/invoice_form.rb
app/views/groups/_actions_show_sac_cas.html.haml
app/views/people/yearly_membership_invoices/new.html.haml
config/locales/wagon.de.yml
config/routes.rb
spec/abilities/sac_cas/group_ability_spec.rb
spec/controllers/people/yearly_membership_invoices_controller_spec.rb
spec/models/people/yearly_membership/invoice_form_spec.rb

Refs: hitobito/hitobito_sac_cas#802

Implement yearly membership invoice interface

---

app/domain/invoices/abacus/subject.rb
app/domain/people/data_quality_checker.rb
app/domain/sac_imports/callback_blacklist.rb
app/jobs/invoices/abacus/transmit_person_job.rb
app/models/group/sektions_mitglieder.rb
app/models/sac_cas/person.rb
spec/models/group/sektions_mitglieder/mitglied_spec.rb
spec/models/person_spec.rb

Transmit person data to abacus

---

app/controllers/people/yearly_membership_invoices_controller.rb
app/jobs/invoices/abacus/create_yearly_invoices_job.rb
app/views/people/yearly_membership_invoices/new.html.haml

Use CreateYearlyInvoicesJob.other_job_running? in frontend

---

app/jobs/invoices/abacus/create_yearly_invoices_job.rb

Refs: https://github.com/hitobito/hitobito/issues/2772 and https://github.com/hitobito/hitobito_sac_cas/issues/803

INVOICE: Add graceful termination to CreateYearlyInvoicesJob

---

app/models/wizards/signup/sektion_wizard.rb
spec/models/wizards/signup/sektion_wizard_spec.rb

Set address of family members during self-registration

---

app/controllers/people/membership_invoices_controller.rb
app/jobs/invoices/abacus/create_invoice_job.rb
spec/jobs/invoices/abacus/create_invoice_job_spec.rb

Fix ArgumentError in create_invoice_job

---

app/models/wizards/memberships/join_zusatzsektion.rb
app/models/wizards/memberships/switch_stammsektion.rb
app/models/wizards/steps/check_data_quality_errors.rb
app/views/wizards/steps/_check_data_quality_errors.html.haml
config/locales/wagon.de.yml
spec/controllers/memberships/switch_stammsektions_controller_spec.rb
spec/features/memberships/join_zusatzsektion_spec.rb
spec/features/memberships/switch_stammsektion_spec.rb
spec/models/wizards/steps/check_data_quality_errors_spec.rb

Validate person attributes in wizard step

---

app/mailers/event/application_confirmation_mailer.rb
app/views/event/participations/_answers_step.html.haml
spec/controllers/event/participations_controller_spec.rb

Fixes current problems in sac_wagon that arose because of changes to Event::Questions in master

fix: changes from master to event_questions

---

app/models/wizards/signup/sektion_operation.rb
spec/features/signup/sektion_spec.rb
spec/models/wizards/signup/sektion_operation_spec.rb

Move self-registration jobs and mailers to wizard

---

app/controllers/events/courses/state_controller.rb
app/mailers/concerns/multilingual_mailer.rb
spec/mailers/event/participation_mailer_spec.rb

Refs https://github.com/hitobito/hitobito/issues/2845
schon mal ein anfang

Sanitize multilingual mails

---

app/domain/people/neuanmeldungen/approve.rb
app/domain/people/neuanmeldungen/base.rb
app/domain/people/neuanmeldungen/reject.rb
app/domain/people/sac_membership.rb
app/mailers/signup/sektion_mailer.rb
app/mailers/signups/sektion_mailer.rb
app/models/wizards/signup/sektion_operation.rb
db/seeds/custom_contents.rb
spec/mailers/signup/sektion_mailer_spec.rb
spec/models/wizards/signup/sektion_operation_spec.rb

Send email for section signup approval

---

app/mailers/invoices/sac_memberships_mailer.rb
db/seeds/custom_contents.rb
spec/mailers/invoices/sac_memberships_mailer.rb

Add mail template for membership activation

---

app/domain/sac_cas/beitragskategorie/calculator.rb
app/models/memberships/join_zusatzsektion.rb
app/models/wizards/memberships/join_zusatzsektion.rb
app/views/wizards/steps/join_zusatzsektion/_summary.html.haml
config/locales/wagon.de.yml
spec/features/memberships/join_zusatzsektion_spec.rb

Update join_zusatzsektion labels

---

app/views/people/_details_sac_cas.html.haml
config/locales/wagon.de.yml
spec/views/people/_details_sac_cas.html.haml_spec.rb

Show `confirmed_at` on `Person#show`

---

app/views/wizards/steps/signup/sektion/_various_fields.html.haml

https://github.com/hitobito/hitobito_sac_cas/actions/runs/10949670842

Self registration reason radio buttons styling

---

app/models/sac_cas/household.rb
config/locales/wagon.de.yml
spec/models/household_spec.rb

Change household email validation

---

app/views/groups/self_registration/_agreement_link.html.haml
app/views/wizards/steps/signup/_agreement_fields.html.haml
spec/features/signup/sektion_spec.rb

Update agreement fields

---

app/abilities/sac_cas/role_ability.rb
app/decorators/sac_cas/group_decorator.rb
app/domain/sac_cas.rb
app/views/roles/_fields.html.haml
spec/features/people/show_spec.rb
spec/features/roles/fields_spec.rb

Prohibit adding/deleting wizard managed roles

---

app/components/self_registration/infos_component.html.haml
config/locales/wagon.de.yml
spec/components/self_registration/infos_component_spec.rb

Add membership card to infos_component

---

app/mailers/event/application_closed_mailer.rb
app/models/concerns/events/courses/state.rb
db/seeds/custom_contents.rb
spec/mailers/event/application_closed_mailer_spec.rb
spec/models/event/course_spec.rb

Send email when course state changes to `application_closed`

---

app/domain/people/data_quality_checker.rb
app/models/sac_cas/person.rb
app/models/sac_cas/phone_number.rb
lib/hitobito_sac_cas/wagon.rb
spec/controllers/people_controller_spec.rb
spec/jobs/people/data_quality_checker_job_spec.rb
spec/models/person_spec.rb

Run data quality check if phone number changed

---

app/domain/sac_imports/wso2_people_importer.rb
app/domain/sac_imports/wso2_person_entry.rb
spec/domain/sac_imports/wso2_people_importer_spec.rb
spec/domain/sac_imports/wso2_person_entry_spec.rb

IMPORT: WSO2 cleanup and fixes

---

app/jobs/event/survey_job.rb
app/mailers/event/survey_mailer.rb
db/seeds/custom_contents.rb
spec/jobs/event/survey_job_spec.rb
spec/mailers/event/application_closed_mailer_spec.rb
spec/mailers/event/participation_mailer_spec.rb
spec/mailers/event/survey_mailer_spec.rb

Send course survey emails

---

app/helpers/sac_cas/standard_form_builder.rb
config/locales/wagon.de.yml
spec/controllers/people_controller_spec.rb
spec/features/event/sign_up_spec.rb
spec/features/event_participation_spec.rb
spec/features/signup/abo_basic_login_spec.rb
spec/features/signup/abo_magazin_spec.rb
spec/features/signup/abo_touren_portal_spec.rb
spec/features/signup/sektion_spec.rb
spec/models/person_spec.rb
spec/models/wizards/signup/sektion_wizard_spec.rb
spec/models/wizards/steps/signup/sektion/family_fields/member_spec.rb
spec/views/wizards/steps/signup/sektion/_summary_family_member_card.html.haml_spec.rb
spec/views/wizards/steps/signup/sektion/_summary_person_card.html.haml_spec.rb

Update wizard labels

---

app/views/wizards/steps/signup/sektion/_family_fields.html.haml
config/locales/wagon.de.yml
spec/features/signup/sektion_spec.rb

Requires https://github.com/hitobito/hitobito/pull/2883
Fixes #985

Update family members step UI

---

CHANGELOG.md
app/abilities/sac_cas/person_ability.rb
spec/abilities/sac_cas/person_ability_spec.rb

Add security ability

---

app/mailers/sac_cas/event/participation_mailer.rb
app/models/concerns/events/courses/state.rb
db/seeds/custom_contents.rb
spec/jobs/qualifications/expiration_mailer_job_spec.rb
spec/mailers/event/participation_mailer_spec.rb
spec/models/event/course_spec.rb

Send email when course participation is rejected

---

app/jobs/event/participant_reminder_job.rb
app/mailers/concerns/event_mailer.rb
app/mailers/event/participant_reminder_mailer.rb
app/models/sac_cas/event/answer.rb
db/seeds/custom_contents.rb
lib/hitobito_sac_cas/wagon.rb
spec/jobs/event/participant_reminder_job_spec.rb
spec/mailers/event/participant_reminder_mailer_spec.rb

Send email reminder to participants with blank answers

---

app/mailers/concerns/event_mailer.rb
db/seeds/custom_contents.rb
spec/controllers/event/participations_controller_spec.rb
spec/controllers/people/sac_family_main_person_controller_spec.rb
spec/domain/invoices/sac_memberships/extend_roles_for_invoicing_spec.rb
spec/domain/invoices/sac_memberships/membership_manager_spec.rb
spec/domain/people/neuanmeldungen/approve_spec.rb
spec/features/memberships/switch_stammsektion_spec.rb
spec/features/people/invoices_spec.rb
spec/features/people/show_spec.rb
spec/features/roles/fields_spec.rb
spec/jobs/event/leader_reminder_job_spec.rb
spec/jobs/event/survey_job_spec.rb
spec/mailers/event/application_confirmation_mailer_spec.rb
spec/mailers/event/participation_mailer_spec.rb
spec/models/event/course_spec.rb
spec/models/group/sektions_mitglieder/mitglied_spec.rb
spec/models/person_spec.rb

Add `participation_price` placeholder to `ApplicationConfirmationMailer`

---

app/models/wizards/steps/signup/abo_magazin/person_fields.rb
app/views/wizards/steps/signup/_common_person_fields.html.haml
config/locales/wagon.de.yml
spec/domain/sac_imports/sac_sections_importer_spec.rb
spec/features/signup/abo_magazin_spec.rb
spec/models/wizards/signup/abo_magazin_wizard_spec.rb

Magazin Signup: allow any birthday, show phone placeholder

---

app/jobs/invoices/abacus/create_course_invoice_job.rb
app/models/concerns/events/courses/state.rb
app/models/external_invoice/course.rb
spec/domain/sac_cas/search_strategies/sql_condition_builder_spec.rb
spec/models/event/course_spec.rb

Enqueue invoice job when course is ready

---

app/views/groups/self_registration/_abo_infos.html.haml
config/locales/wagon.de.yml
spec/views/groups/_abo_infos.html.haml_spec.rb

Add info text to `self_registration/_abo_infos`

---

app/models/sac_cas/event/course.rb
app/resources/sac_cas/event/course_resource.rb
app/views/events/_attrs_primary_sac_cas.html.haml
app/views/events/_form_tab_pane_prices.html.haml
app/views/events/_form_tabs_sac_cas.html.haml
config/locales/wagon.de.yml
spec/features/events_spec.rb
spec/resources/sac_cas/event/course_resource_spec.rb
spec/support/graphiti/schema.json

EVENTS: Kurspreise bearbeiten und darstellen 

---

config/initializers/render_comments.rb

teilweise übernommen von @largo

Add comments which partial is rendered in development

---

app/models/sac_cas/event/course.rb
app/views/events/_attrs_application.html.haml
config/locales/wagon.de.yml
db/migrate/20240930110139_add_events_canceled_reason.rb
spec/models/event/course_spec.rb
spec/views/events/_attrs.html.haml_spec.rb

Fixes #580
popover ist in #1067 damit es nicht zu lange dieses ticket blockiert

Add canceled_reason to course

---

app/models/wizards/steps/signup/abo_basic_login/person_fields.rb
app/models/wizards/steps/signup/abo_touren_portal/person_fields.rb
app/models/wizards/steps/signup/agreement_fields.rb
app/views/wizards/steps/signup/_person_fields.html.haml
app/views/wizards/steps/signup/abo_basic_login/_person_fields.html.haml
app/views/wizards/steps/signup/abo_magazin/_issues_from_field.html.haml
config/locales/wagon.de.yml
spec/features/signup/abo_basic_login_spec.rb
spec/models/wizards/signup/abo_basic_login_wizard_spec.rb

Update `AboBasicLogin` wizard form

---

app/mailers/event/canceled_mailer.rb
app/models/concerns/events/courses/state.rb
db/seeds/custom_contents.rb
spec/mailers/event/canceled_mailer_spec.rb
spec/models/event/course_spec.rb

Send email when course is canceled

---

app/domain/sac_imports/csv_source.rb
app/domain/sac_imports/qualification_entry.rb
app/domain/sac_imports/qualifications_importer.rb
lib/tasks/sac_imports.rake
spec/domain/sac_imports/csv_source_spec.rb
spec/domain/sac_imports/qualifications_importer_spec.rb

PEOPLE: Import Qualifikationen (aus NAV3)

---

config/locales/wagon.de.yml
spec/features/signup/sektion_spec.rb

Remove 'optional' labels for self registration family members form

---

app/assets/stylesheets/hitobito/customizable/_wagon.scss
app/views/wizards/steps/signup/_common_person_fields.html.haml
app/views/wizards/steps/signup/sektion/_family_fields.html.haml
config/locales/wagon.de.yml
spec/features/signup/abo_magazin_spec.rb

Requires hitobito/hitobito#2903
Fixes #1043

Update birthday field in wizards

---

app/domain/sac_imports/family_importer.rb
doc/import.md
lib/tasks/sac_imports.rake
spec/domain/sac_imports/family_importer_spec.rb

Implement SacImports::FamilyImporter

---

app/views/wizards/steps/signup/abo_magazin/_person_info_table.html.haml
config/locales/wagon.de.yml
spec/domain/export/tabular/people/sac_recipient_households_spec.rb
spec/domain/export/tabular/people/sac_recipients_spec.rb
spec/views/wizards/steps/signup/abo_magazin/_person_info_table.html.haml_spec.rb
spec/views/wizards/steps/signup/sektion/_summary_person_card.html.haml_spec.rb

Cosmetic changes in signup wizards

---

app/controllers/sac_cas/event/participations_controller.rb
spec/controllers/event/participations_controller_spec.rb

Enqueue invoice job when participant is summoned

---

app/domain/invoices/sac_memberships/membership_manager.rb
spec/domain/invoices/sac_memberships/membership_manager_spec.rb

Send membership activation email in membership_manager

---

app/controllers/events/courses/invoices_controller.rb
app/views/event/participations/_actions_show_sac_cas.html.haml
config/locales/wagon.de.yml
config/routes.rb
spec/controllers/events/courses/invoices_controller_spec.rb
spec/features/event/participation_spec.rb
spec/features/event/sign_up_spec.rb

Add button to create participation invoice

---

app/models/memberships/common_api.rb
app/models/memberships/switch_stammsektion.rb
app/models/memberships/terminate_sac_membership.rb
spec/models/memberships/join_base_spec.rb
spec/models/memberships/switch_stammsektion_spec.rb

Delete old role on stammsektion switch

---

app/helpers/sac_cas/standard_form_builder.rb
app/models/wizards/signup/sektion_operation.rb
app/models/wizards/steps/signup/sektion/family_fields/member.rb
app/models/wizards/steps/signup/sektion/person_fields.rb
spec/features/signup/sektion_spec.rb
spec/models/wizards/signup/sektion_operation_spec.rb
spec/models/wizards/signup/sektion_wizard_spec.rb
spec/models/wizards/steps/signup/sektion/family_fields/member_spec.rb
spec/models/wizards/steps/signup/sektion/family_fields_spec.rb
spec/models/wizards/steps/signup/sektion/person_fields_spec.rb

Fixes #1100
[Dieser Change](https://github.com/hitobito/hitobito_sac_cas/pull/992/files#diff-2667a16d00837710fd5f140ec54e861ab52a5571e7780379122b8f65746790e7) führte zu dem Bug

Fix form builder deselecting gender radio buttons

---

app/controllers/people/external_invoices_controller.rb
config/routes.rb
spec/controllers/people/external_invoices_controller_spec.rb
spec/requests/hitobito_log_entries_controller_spec.rb

Ref: https://github.com/hitobito/hitobito_sac_cas/issues/1124
Fixes the links in `hitobito_log_entries/rechnungen`

Fix external invoice links in hitobito log

---

app/views/events/_list_table.html.haml

Show event number in course list

---

app/controllers/sac_cas/event/participations_controller.rb
app/domain/invoices/abacus/course_invoice.rb
config/locales/wagon.de.yml
spec/controllers/event/participations_controller_spec.rb
spec/domain/invoices/abacus/course_invoice_spec.rb
spec/domain/invoices/abacus/membership_invoice_spec.rb

Cancel invoice after participation cancellation

---

app/decorators/sac_cas/event/participation_decorator.rb
app/domain/sac_cas.rb
app/views/event/participations/_fields_sac_cas.html.haml
config/locales/wagon.de.yml
spec/features/event/participation_edit_spec.rb

Improve participation price dropdown

---

app/models/sac_cas/role/active_membership_validations.rb
app/models/sac_cas/role/mitglied_zusatzsektion.rb
spec/models/group/sektions_mitglieder/ehrenmitglied_spec.rb
spec/models/group/shared_examples_mitglied_dependant_destroy.rb
spec/models/group/shared_examples_mitglied_role_required.rb

Update ActiveMembershipValidations to account for concurrent memberships (#1117)

---

app/abilities/json_api/event/level_ability.rb
app/abilities/json_api/external_invoice_ability.rb
app/controllers/json_api/event/levels_controller.rb
app/resources/event/level_resource.rb
app/resources/sac_cas/event_resource.rb
config/routes.rb
lib/hitobito_sac_cas/wagon.rb
spec/api/event_levels/index_spec.rb
spec/api/event_levels/show_spec.rb
spec/api/events/index_spec.rb
spec/fabricators/event_level_fabricator.rb
spec/support/graphiti/schema.json

Add `Event::Level` API endpoint

---

db/seeds/groups.rb

Seed correct selfreg role type in magazin abo groups

---

app/views/groups/_attrs_sac_cas.html.haml
config/locales/wagon.de.yml
spec/views/groups/_attrs_sac_cas.html.haml_spec.rb

Show sti_name / type of group in group info tab

---

app/controllers/sac_cas/event/participations_controller.rb
spec/controllers/event/participations_controller_spec.rb

refs: https://github.com/hitobito/hitobito_sac_cas/issues/1014
https://github.com/hitobito/hitobito_sac_cas/issues/1014#issuecomment-2441254997
https://github.com/hitobito/hitobito_sac_cas/issues/1014#issuecomment-2443739627

Create course annulation invoice after participation cancel

---

app/views/wizards/steps/termination/_summary.html.haml
config/locales/wagon.de.yml
config/locales/wagon.en.yml
config/locales/wagon.fr.yml
config/locales/wagon.it.yml
spec/features/memberships/sac_terminate_membership_wizard_spec.rb

Ref: #1205 
Depends on https://github.com/hitobito/hitobito/pull/2980
Current UI

Feature/1205 SAC termination wizard fixes

---

db/seeds/development/3_event_kinds_and_qualifications.rb

Seed event_kind short_names

---

app/models/sac_cas/household_member.rb
app/models/sac_cas/person.rb
spec/models/household_member_spec.rb
spec/models/household_spec.rb

Add household validation to ensure not having any terminated membership

---

config/locales/wagon.de.yml
spec/features/memberships/join_zusatzsektion_spec.rb

Die Translations in Transifex habe ich bereits getauscht.

Fix swapped translations, fixes #1254

---

spec/models/household_spec.rb

https://github.com/hitobito/hitobito_sac_cas/actions/runs/11834775411

Add spec for sac case

---

app/views/event/participations/_roles_sac_cas.html.haml
app/views/event/roles/_fields_sac_cas.html.haml
spec/controllers/event/participations_controller_spec.rb
spec/features/event_participation_spec.rb
spec/features/events_spec.rb
spec/requests/event/roles_controller_spec.rb

Only show self employed checkbox and field for leaders

---

app/domain/people/neuanmeldungen/base.rb
spec/controllers/people/neuanmeldungen/approves_controller_spec.rb
spec/controllers/people/neuanmeldungen/rejects_controller_spec.rb
spec/domain/people/neuanmeldungen/approve_spec.rb

Only include household people when neuanmeldungs role is family

---

app/abilities/memberships/switch_stammsektion_ability.rb
spec/features/memberships/switch_stammsektion_spec.rb

https://github.com/user-attachments/assets/7bd19f09-2f0a-4c37-ba47-add6f0f9a417

Berechtigungsanpassung: Mitglieder sollen keine Sektionswechsel beantragen können

---

app/abilities/section_offering_ability.rb
app/controllers/section_offerings_controller.rb
app/helpers/sheet/section_offering.rb
app/models/group/sektion.rb
app/models/section_offering.rb
app/resources/sac_cas/group_resource.rb
app/views/groups/_attrs_sac_cas.html.haml
app/views/groups/_general_fields_sac_cas.html.haml
app/views/section_offerings/_form.html.haml
app/views/section_offerings/_list.html.haml
app/views/shared/_admin_nav_main_sac_cas.html.haml
config/locales/wagon.de.yml
config/routes.rb
db/migrate/20241209075525_add_section_offerings.rb
db/seeds/development/7_section_offerings.rb
lib/hitobito_sac_cas/wagon.rb
spec/abilities/section_offering_ability_spec.rb
spec/features/group_show_spec.rb
spec/models/section_offering_spec.rb
spec/support/graphiti/schema.json

spec run with core branch: https://github.com/hitobito/hitobito_sac_cas/actions/runs/12272262501

Add section offerings table

---

config/locales/wagon.de.yml

Change devise unlock_instructions email footer

---

app/views/groups/_general_fields_sac_cas.html.haml
spec/requests/groups_controller_spec.rb

Fix/1417 Can't edit groups

---

config/locales/wagon.de.yml
spec/features/event/sign_up_spec.rb

Change text in event participation confirmation

---

config/locales/wagon.de.yml
spec/components/self_registration/infos_component_spec.rb

Adjust wizard document links

---

config/locales/wagon.de.yml

Update course onboarding wizard links

---

app/models/wizards/signup/sektion_wizard.rb
spec/features/people/invoices_spec.rb

Adjust sektion signup for core changes

---

app/jobs/export/backup_mitglieder_export_job.rb
spec/jobs/export/backup_mitglieder_export_job_spec.rb

Export::BackupMitgliederExportJob: fix upload path

---

app/domain/people/sac_membership.rb
app/domain/table_displays/resolving_column.rb
app/jobs/sac_cas/export/people_export_job.rb

https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74119
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74116

Extend select to fix table display render and export issues (#1508)

---

app/domain/sac_cas/table_displays/login_status_column.rb
lib/hitobito_sac_cas/wagon.rb
spec/domain/table_displays/people/login_status_column_spec.rb
spec/domain/table_displays/resolving_column_spec.rb
spec/features/people/list_spec.rb

Fix table display login status column

---

app/domain/table_displays/people/address_valid_column.rb
app/domain/table_displays/people/antrag_fuer_column.rb
app/domain/table_displays/people/antragsdatum_column.rb
app/domain/table_displays/people/beitragskategorie_column.rb
app/domain/table_displays/people/beitrittsdatum_column.rb
app/domain/table_displays/people/confirmed_at_column.rb
app/domain/table_displays/people/duplicate_exists_column.rb
app/domain/table_displays/people/self_registration_reason_column.rb
app/domain/table_displays/people/wiedereintritt_column.rb
spec/domain/table_displays/people/antrag_fuer_column_spec.rb
spec/domain/table_displays/people/antragsdatum_column_spec.rb
spec/domain/table_displays/people/beitrittsdatum_column_spec.rb
spec/domain/table_displays/people/login_status_column_spec.rb

https://github.com/hitobito/hitobito_sac_cas/actions/runs/12934359939

Fix all table display columns not exporting correct values (#1593)

---

app/domain/invoices/sac_memberships/membership_manager.rb
spec/domain/invoices/sac_memberships/membership_manager_spec.rb

Sentry issue: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74547

Add null safe approach in extend_membership_duration

---

README.md
config/locales/wagon.de.yml
doc/hierarchy.md

Labels of group types must be unique

Fix label for SektionsTourenUndKurseAllgemein (HIT-1013)

---

app/models/group/sektions_mitglieder.rb
app/models/memberships/common_api.rb
app/models/memberships/family_mutation.rb
app/models/memberships/switch_stammsektion.rb
app/models/sac_cas/household.rb
app/models/sac_cas/role/mitglied_common.rb
spec/models/group/sektions_mitglieder/mitglied_spec.rb
spec/models/group/shared_examples_mitglied_dependant_destroy.rb
spec/models/household_spec.rb
spec/models/memberships/switch_stammsektion_spec.rb

Fix multiple membership mutations on same day (#1581)

---

app/jobs/event/close_applications_job.rb
app/mailers/event/application_closed_mailer.rb
app/mailers/event/application_confirmation_mailer.rb
app/mailers/event/application_paused_mailer.rb
app/mailers/event/canceled_mailer.rb
app/mailers/event/leader_reminder_mailer.rb
app/mailers/event/participation_canceled_mailer.rb
app/mailers/event/published_mailer.rb
app/mailers/event/survey_mailer.rb
app/mailers/sac_cas/event/participation_mailer.rb
app/models/concerns/events/courses/state.rb
spec/jobs/event/close_applications_job_spec.rb
spec/jobs/event/leader_reminder_job_spec.rb
spec/mailers/event/application_closed_mailer_spec.rb
spec/mailers/event/application_confirmation_mailer_spec.rb
spec/mailers/event/canceled_mailer_spec.rb
spec/mailers/event/participation_canceled_mailer_spec.rb
spec/mailers/event/participation_mailer_spec.rb
spec/mailers/event/survey_mailer_spec.rb
spec/models/event/course_spec.rb

fixes: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74967

Use Group.root to get course_admin_email

---

app/jobs/invoices/abacus/create_yearly_abo_alpen_invoices_job.rb
app/models/wizards/signup/abo_magazin_wizard.rb
config/settings.yml
config/settings/test.yml
spec/jobs/invoices/abacus/create_yearly_abo_alpen_invoices_job_spec.rb
spec/models/wizards/signup/abo_magazin_wizard_spec.rb

review and merge https://github.com/hitobito/hitobito_sac_cas/pull/1704 first
related: https://gitlab.puzzle.ch/pitc_hit/deployments/hitobito/-/merge_requests/24

Feature/1694/disable abo invoicing (#1694)

---

app/abilities/event_kind_readables.rb
spec/abilities/event_kind_readables_spec.rb

Refs: hitobito/hitobito_sac_cas#1646

Fix checking permissions on event kind readables

---

app/views/event/participations/_popover_participant_cancels.html.haml
spec/features/event_participation_spec.rb

Refs: hitobito/hitobito_sac_cas#1551

Only show cancellation costs info for participations not on waiting list

---

app/jobs/people/sac_memberships/destroy_households_for_inactive_memberships_job.rb
lib/hitobito_sac_cas/wagon.rb
spec/jobs/people/sac_memberships/destroy_households_for_inactive_memberships_job_spec.rb

- **Add family cleanup job for ended stammsektion roles (#1641)**
- **Reschedule in time zone**
- **Fix query to not include people with active family memberships**

Add family cleanup job for ended stammsektion roles (#1641)

---

app/models/sac_cas/event/participation_contact_data.rb
spec/features/event_participation_spec.rb
spec/models/event/participation_contact_data_spec.rb

https://github.com/hitobito/hitobito_sac_cas/actions/runs/14123505801
~~Feature spec is still missing :upside_down_face:~~

Mark phone_number fields as required on event signup (#1699)

---

spec/api/events/index_spec.rb

https://github.com/hitobito/hitobito_sac_cas/actions/runs/14383535461

Add spec to check for updated event after date changes (#3321)

---

app/models/memberships/family_mutation.rb
spec/models/memberships/family_mutation_spec.rb

https://sentry.puzzle.ch/pitc/hitobito-backend/issues/76039/

Add check for start_on to prevent error in family mutation

---

app/models/memberships/undo_termination.rb
app/views/memberships/undo_terminations/new.html.haml
spec/controllers/event/register_controller_spec.rb
spec/controllers/groups/self_registration_controller_spec.rb
spec/features/memberships/sac_terminate_membership_wizard_spec.rb
spec/features/signup/abo_basic_login_spec.rb
spec/fixtures/groups.yml
spec/models/memberships/terminate_sac_membership_spec.rb
spec/models/memberships/undo_termination_spec.rb
spec/models/wizards/signup/abo_basic_login_wizard_spec.rb
spec/views/memberships/undo_terminations/new.html.haml_spec.rb

- **Add AboBasicLogin in groups fixtures**
- **Teach UndoTermination to remove roles created by termination #1726**

Teach UndoTermination to remove roles created by termination #1726

---

app/controllers/sac_cas/event/participations_controller.rb
spec/controllers/event/participations_controller_spec.rb

Refs: https://github.com/hitobito/hitobito_sac_cas/issues/1843
Requires: https://github.com/hitobito/hitobito_youth/pull/115

Refresh participant count for event on participation reactivate

---

app/abilities/sac_cas/group_ability.rb
app/assets/javascripts/download_statistics.js
app/assets/javascripts/wagon.js.coffee
app/helpers/sac_cas/groups_helper.rb
app/views/groups/_actions_show_sac_cas.html.haml
app/views/groups/_popover_download_statistics.html.haml
config/locales/wagon.de.yml
config/settings.yml
spec/abilities/sac_cas/group_ability_spec.rb
spec/features/groups/download_membership_statistics_spec.rb
spec/views/groups/_actions_show_sac_cas.html.haml_spec.rb

refs: hitobito/hitobito_sac_cas#1900

Add membership statistics download popover

---

app/models/wizards/steps/termination/summary.rb
app/views/wizards/steps/termination/_summary.html.haml
config/locales/wagon.de.yml
config/locales/wagon.fr.yml
config/locales/wagon.it.yml
spec/features/memberships/sac_terminate_membership_wizard_spec.rb

Anpassungen im Transifex hab ich schon gemacht

Add termination checkbox (#1877)

---

app/abilities/sac_cas/group_ability.rb
app/models/group/sektions_funktionaere.rb
config/locales/wagon.de.yml
lib/hitobito_sac_cas/wagon.rb
spec/abilities/sac_cas/group_ability_spec.rb
spec/fixtures/people.yml
spec/models/group/sektions_funktionaere_spec.rb

Allow Sektionsfunktionäre to download member statistics #1912

---

app/models/concerns/roles/abacus_transmittable.rb
app/models/wizards/signup/abo_magazin_wizard.rb
spec/fixtures/groups.yml
spec/models/wizards/signup/abo_magazin_wizard_spec.rb

Requires https://github.com/hitobito/hitobito/pull/3548

Skip transmit to abacus in abo magazin wizard (#1861)

---

app/models/wizards/steps/signup/abo_magazin/person_fields.rb
spec/models/wizards/steps/signup/abo_magazin/person_fields_spec.rb

Refs: hitobito/hitobito_sac_cas#1952

Prefill company from person when registering for abo magazin

---

app/views/event/participations/_summary_step.html.haml
config/settings.yml
spec/features/event/events_controller_spec.rb
spec/features/event/participation_spec.rb
spec/models/event/answer_spec.rb
spec/models/event_spec.rb

Configure alphabetic question sorting
