hitobito/hitobito_sac_cas

- app/resources/sac_cas/group_resource.rb
- lib/hitobito_sac_cas/wagon.rb
- spec/resources/sac_cas/group_resource_spec.rb
> Add navision and mounted_attrs to group resource

- app/models/sac_cas/group.rb
- app/views/groups/_attrs_sac_cas.html.haml
- config/locales/wagon.de.yml
- spec/views/groups/_attrs_sac_cas.html.haml_spec.rb
Anpassungen an der view sind gemacht. Das Naming `Sektion-ID` für `group#id` bei den Ortsgruppen finde ich aber problematisch. 
Auch ob es tatsächlich noch API anpassungen braucht ist mir nicht klar, beide Attribute sind ja schon im API drinnen als (`id` bzw `navision_id`)
> Display attrs on group#show

- app/controllers/sac_cas/event/kind_categories_controller.rb
- app/models/sac_cas/event/kind_category.rb
- app/views/event/kind_categories/_actions_edit.html.haml
- config/locales/wagon.de.yml
- config/routes.rb
- lib/hitobito_sac_cas/wagon.rb
- spec/controllers/event/kind_categories_controller_spec.rb
- spec/fixtures/event/kinds.yml
- spec/models/event/kind_category_spec.rb
Das im ticket beschriebene icon existiert in Fontawesome 5 nicht, ich hab jetzt was analoges genommen.
> Add button to push cost models from kind_category to kind, (#359)

- app/models/group/sac_cas.rb
- config/locales/wagon.de.yml
- spec/models/group/sac_cas_spec.rb
refs #504
@codez Die zwei Attribute 
-  "Die Alpen Abo ID" / `sac_magazine_mailing_list_id`
- "SAC Magazin Abo ID" / `sac_magazin_mailing_list_id`
sind sehr nah beisammen, wäre nicht "Die Alpen Abo ID" / `sac_alps_mailing_list_id` naheliegender?
> Add additional mailing_lists as mounted attrs to root, (#504)

- app/helpers/sac_cas/people_helper.rb
- app/models/sac_cas/person.rb
- app/views/people/_details_sac_cas.html.haml
- app/views/people/_fields_sac_cas.html.haml
- config/locales/wagon.de.yml
- db/migrate/20240514093001_change_people_correspondence_to_enum.rb
- lib/hitobito_sac_cas/wagon.rb
- spec/models/person_spec.rb
Refs: hitobito/hitobito_sac_cas#485
Auslöser war, dass das Flag im Log unverständlich angezeigt wurde: https://github.com/hitobito/hitobito_sac_cas/issues/485#issuecomment-2096413426
Als Lösung darauf wollte ich lieber nicht im PaperTrail decorator herumbasteln sondern fand es leichter das ganze einfach auf ein `i18n_enum` umzubauen. Das ist auch so mit dem Lead BA/DEV abgesprochen.
Hier wird das Flag jetzt nicht korrekt migriert, ist aber glaube ich auch nicht nötig, da das Ticket ja sowieso nicht abgeschlossen war.
> Change digital_correspondence to correspondence enum field

- app/domain/sac_cas.rb
- app/domain/sac_cas/oidc_claim_setup.rb
- config/locales/wagon.de.yml
- lib/hitobito_sac_cas/wagon.rb
- spec/controllers/oauth/userinfo_controller_spec.rb
- spec/domain/oidc_claim_setup_spec.rb
- spec/requests/oauth_profile_spec.rb
Mir ist noch nicht ganz klar, warum in `spec/requests/oauth_profile_spec.rb` der `with_groups` scope nicht alleine funktioniert (sonder nur in kombination mit name). Weist da jemand was? Sollen wir das noch vertieft anschauen?
> Feature/sac 428 custom OIDC claims

- db/seeds/development/0_groups.rb
* Assign parent instead of just parent_id, so the before_save hook runs properly
* Adapt to new group structure where SektionsHuettenkommission is below SektionsFunktionaere
Related PRs:
* Wrong fix for the seeding error because parent: https://github.com/hitobito/hitobito/pull/2648.
* Validation for parent https://github.com/hitobito/hitobito/pull/2655
> Fix group seeds

- config/locales/wagon.fr.yml
Useful when testing the locale aware group sorting.
Ref: https://github.com/hitobito/hitobito/issues/2673
> Add french translations for group names

- app/components/sac_cas/steps_component/content_component.rb
- app/models/wizards/steps/main_email.rb
- app/views/wizards/steps/_main_email.html.haml
- config/locales/wagon.de.yml
- spec/components/previews/wizards_preview.rb
- spec/models/wizards/steps/main_email_spec.rb
- spec/views/wizards/steps/_main_email.html.haml_spec.rb
> Add MainEmail wizard step

- app/helpers/dropdown/events/courses/state.rb
- app/models/concerns/events/courses/state.rb
- config/locales/wagon.de.yml
- spec/models/event/course_spec.rb
fixes #583 
Basically done except:
this is missing the special return text for the buttons. It might be confusing for the user at this state
"Anmeldung abschliessen" instead of "Zurück zur abgeschlossenen Anmeldung"
>  EVENTS: Zusätzliche Statuswechsel #583

- app/abilities/sac_cas/role_ability.rb
- app/domain/groups/primary.rb
- app/domain/people/sac_family.rb
- app/domain/people/sac_membership.rb
- app/domain/sac_cas.rb
- app/domain/table_displays/resolver.rb
- app/models/group/sektions_mitglieder.rb
- app/models/group/sektions_neuanmeldungen_nv.rb
- app/models/group/sektions_neuanmeldungen_sektion.rb
- app/models/sac_cas/event/participation.rb
- app/models/sac_cas/role.rb
- app/models/sac_cas/role/mitglied_family_validations.rb
- app/models/sac_cas/role/mitglied_no_overlap_validation.rb
- app/models/sac_cas/role/mitglied_stammsektion.rb
- config/locales/wagon.de.yml
- spec/abilities/sac_cas/role_ability_spec.rb
- spec/domain/table_displays/resolver_spec.rb
- spec/features/roles/terminations_spec.rb
- spec/models/future_role_spec.rb
- spec/models/group/mitglied_no_overlap_validation_spec.rb
- spec/models/household_spec.rb
Die Konstanten hatten ungenaue, irreführende Namen und wurden entsprechend auch schon falsch verwendet.
Dieser commit passt die Konstanten Namen an für bessere Verständlichkeit.
> SacCas Konstanten Namen verbessern

- app/models/memberships/family_mutation.rb
- app/views/people/_people_managers_aside.html.haml
- spec/features/people/managers_spec.rb
- spec/models/memberships/family_mutations_spec.rb
* Prevent crash in Memberships::FamilyMutation#leave! when person has no
stammsektion membership
* hide people manager aside on person show view
Fixes #712
> Fix Memberships::FamilyMutation#leave!, hide people manager aside

- app/views/wizards/steps/_termination_choose_date.html.haml
- app/views/wizards/steps/leave_zusatzsektion/_no_self_service.html.haml
- config/locales/wagon.de.yml
- spec/requests/memberships/leave_zusatzsektions_controller_spec.rb
Ref: #627 
Testing:
* Impersonate as an admin: http://localhost:3000/de/groups/8/people/600780.html (Carlo Beltrame)
* Go to a persons history which is a Mitglied (Zusatzsektion) http://localhost:3000/de/groups/36/people/600047/history (Nick Harter)
* Set `mitglied_termination_by_section_only` to `true` for the affected layer: `Role.find(47).layer_group.tap { |l| l.update!(mitglied_termination_by_section_only: true) }`
> Feature/627 Show warning in choose date step in austritt zusatzsektion wizard

- app/abilities/course_compensation_category_ability.rb
- app/controllers/course_compensation_categories_controller.rb
- app/helpers/sheet/course_compensation_category.rb
- app/models/course_compensation_category.rb
- app/models/course_compensation_rate.rb
- app/models/event/level.rb
- app/models/external_invoice.rb
- app/models/external_invoice/course.rb
- app/models/external_invoice/sac_membership.rb
- app/models/external_training.rb
- app/models/sac_membership_config.rb
- app/models/sac_section_membership_config.rb
- app/models/termination_reason.rb
- app/views/course_compensation_categories/_form.html.haml
- app/views/course_compensation_categories/_list.html.haml
- app/views/shared/_admin_nav_main_sac_cas.html.haml
- config/routes.rb
- lib/hitobito_sac_cas/wagon.rb
- spec/abilities/course_compensation_category_ability_spec.rb
- spec/controllers/course_compensation_categories_controller_spec.rb
- spec/fixtures/event/levels.yml
- spec/fixtures/sac_membership_configs.yml
- spec/fixtures/sac_section_membership_configs.yml
Die Seeds zu dem Thema sind im PR #740.
https://github.com/user-attachments/assets/1cb60c08-f7f5-4ac3-9c72-356564365774
In diesem PR habe ich mir erlaubt die von `annotate` generierten Schema Information vom SAC Wagon zu aktualisieren.
> EVENTS: Einstellungen Kursvergütungskategorien

- app/resources/sac_cas/person_resource.rb
- spec/api/people/show_spec.rb
- spec/resources/person/reads_spec.rb
- spec/support/graphiti/schema.json
Fixes #518
- Testbar auf z.B. http://localhost:3000/api/people/600780
- Wenn man keine Berechtigungen hat, ein `remark` feld zu sehen, wird dies in der API trotzdem angezeigt, aber immer mit `null` als Wert
> PEOPLE: Bemerkungsfelder in API

- app/abilities/sac_cas/person_ability.rb
- spec/abilities/sac_cas/person_ability_spec.rb
- spec/api/people/show_spec.rb
- spec/controllers/person/sac_remarks_controller_spec.rb
- spec/domain/table_displays/resolver_spec.rb
Fixes #511
Refs https://github.com/hitobito/hitobito_sac_cas/issues/511#issuecomment-2242477708
Nun kann die Geschäftsstelle alle Remarks sehen
> PEOPLE: Bemerkungsfelder Berechtigungen fix

- db/migrate/20240522065606_delete_obsolete_roles_and_groups.rb
- db/migrate/20240529120000_move_huetten_into_sektionsfunktionaere.rb
- db/migrate/20240605120000_move_more_groups_into_sektionsfunktionaere.rb
This help to distinguish between the SQL-literal GROUPS and the table-name for Group-Objects. Not strictly needed for the current version of mysql in production, but I do not want to be surprised be this.
> Quote tablename for groups

- app/jobs/event/leader_reminder_job.rb
- app/mailers/event/leader_reminder_mailer.rb
- app/mailers/sac_cas/application_mailer.rb
- db/seeds/custom_contents.rb
- lib/hitobito_sac_cas/wagon.rb
- spec/jobs/event/leader_reminder_job_spec.rb
Fixes #629
zum testen auf localhost:
```ruby
Event::Course.first.dates.first.update! start_at: 8.weeks.from_now.to_date, finish_at: 9.weeks.from_now.to_date
Event::Course.first.groups.first.update! course_admin_email: 'admin@example.com'
Event::LeaderReminderJob.new.perform
```
dann im mailcatcher schauen. sprache bearbeitbar auf http://localhost:3000/de/groups/1/events/1/edit
> EVENTS: E-Mail Reminder Kursleitung

- app/domain/sac_cas/oidc_claim_setup.rb
- app/models/group/abo_magazin.rb
- app/models/group/abo_magazine.rb
- app/models/group/abo_touren_portal.rb
- app/models/group/abos.rb
- app/models/group/sac_cas.rb
- config/locales/wagon.de.yml
- config/locales/wagon.en.yml
- config/locales/wagon.fr.yml
- config/locales/wagon.it.yml
- db/seeds/groups.rb
- spec/domain/oidc_claim_setup_spec.rb
- spec/features/signup/abo_basic_login_spec.rb
- spec/features/signup/abo_touren_portal_spec.rb
- spec/fixtures/groups.yml
- spec/models/memberships/terminate_sac_membership_spec.rb
- spec/models/wizards/signup/abo_basic_login_wizard_spec.rb
- spec/models/wizards/signup/abo_magazin_wizard_spec.rb
- spec/models/wizards/signup/abo_touren_portal_wizard_spec.rb
Beim Review:
Nach dem Review:
```ruby
Group.where(type: "Group::Abonnenten").each { |group| group.children.each(&:really_destroy!) }
Group.where(type: "Group::Abonnenten").each { |group| group.really_destroy! }
Group.where(type: "Group::AboTourenPortal").each { |group| group.really_destroy! }
Group.where(type: "Group::AboBasicLogin").each { |group| group.really_destroy! }
```
Nach dem Merge:
> GROUPS: Anpassungen Gruppenstruktur Toplayer > Abonnenten

- app/models/memberships/join_base.rb
- app/models/memberships/join_zusatzsektion.rb
- app/models/memberships/switch_stammsektion.rb
- app/models/wizards/memberships/join_zusatzsektion.rb
- app/models/wizards/memberships/switch_stammsektion.rb
- config/locales/wagon.de.yml
- spec/models/memberships/join_base_spec.rb
- spec/models/memberships/join_zusatzsektion_spec.rb
- spec/models/memberships/switch_stammsektion_spec.rb
Reviewed im #811, ging bei force push verloren
> PEOPLE: Stammsektionwechsel nur per sofort erlauben (2/2)

- app/jobs/event/leader_reminder_job.rb
- app/jobs/event/published_job.rb
- app/mailers/event/leader_reminder_mailer.rb
- app/mailers/event/published_mailer.rb
- app/models/sac_cas/event/course.rb
- spec/jobs/event/leader_reminder_job_spec.rb
- spec/models/event/course_spec.rb
Fixes #599 (#804)
Fixes #629
Fixes #634
alle fixes sind das gleiche: `course.contact` -> `leaders`
sendet jede mail einzeln mit dem richtigen empfänger
siehe #765 zur testanleitung oder `kurs -> entwurf -> publizieren`
> EVENTS: E-Mail Kursveröffentlichung Empfänger fix

- app/domain/qualifications/expiring.rb
- app/jobs/qualifications/expiration_mailer_job.rb
- app/mailers/qualifications/expiration_mailer.rb
- spec/jobs/qualifications/expiration_mailer_job_spec.rb
refs #260
Da die einen Mails nur am 31.12. verschickt werden, kann dieses Feature kaum getestet werden. Deshalb werden temporär täglich alle E-Mails verschickt. Sobald das Ticket abgenommen ist, wird der entsprechende Kommentar wieder entfernt. (Nicht aber die anderen Changes ;)
> Send daily qualification expiration mails for integration testing

- app/controllers/sac_cas/event/participations_controller.rb
- app/domain/sac_cas/event/participant_assigner.rb
- app/jobs/event/application_confirmation_job.rb
- app/mailers/concerns/event_mailer.rb
- app/mailers/event/application_confirmation_mailer.rb
- config/locales/wagon.de.yml
- db/seeds/custom_contents.rb
- lib/hitobito_sac_cas/wagon.rb
- spec/controllers/event/participations_controller_spec.rb
Fixes #625
**Auf localhost testen**
Kursanmeldung bestätigt: [hier](http://localhost:3000/de/groups/1/events/1/participations/new?event_role[type]=Event%3A%3ACourse%3A%3ARole%3A%3AParticipant&for_someone_else=true) einen teilnehmer hinzufügen
Unbestätigte Kursanmeldung: [hier](http://localhost:3000/de/groups/1/events/1/register) selbst registrieren
> EVENTS: E-Mail Anmeldebestätigung

- app/domain/table_displays/resolver.rb
- app/domain/table_displays/resolving_column.rb
- app/helpers/sac_cas/people_helper.rb
- config/locales/wagon.de.yml
- lib/hitobito_sac_cas/wagon.rb
- spec/domain/table_displays/resolving_column_spec.rb
- spec/features/people/list_spec.rb
> PEOPLE: Data quality in TableDisplay

- app/domain/people/data_quality_checker.rb
- app/models/person/data_quality_issue.rb
- app/models/sac_cas/person.rb
- app/models/sac_cas/role/mitglied_common.rb
- config/locales/wagon.de.yml
- spec/fabricators/person_data_quality_issue_fabricator.rb
- spec/features/people/show_spec.rb
- spec/models/person/data_quality_issue_spec.rb
- spec/models/person_spec.rb
> PEOPLE: Data quality checker

- app/models/sac_cas/role.rb
- spec/domain/invoices/sac_memberships/member_spec.rb
- spec/domain/invoices/sac_memberships/position_generator_spec.rb
- spec/models/person_spec.rb
- spec/models/role_spec.rb
For PostgreSQL we have to adjust the query a little bit, here is the PostgreSQL conform version of the new query:
```
CASE
-- membership_years is only calculated for Mitglied roles
WHEN roles.type != 'Group::SektionsMitglieder::Mitglied' THEN 0
ELSE (
EXTRACT(
YEAR FROM age(
LEAST(
DATE('#{date.strftime("%Y-%m-%d")}'),
COALESCE(
DATE(CONVERT_TZ(roles.deleted_at, 'UTC', 'CET')) + INTERVAL '1 day',
'9999-12-31'
),
COALESCE(
DATE(CONVERT_TZ(roles.archived_at, 'UTC', 'CET')) + INTERVAL '1 day',
'9999-12-31'
),
COALESCE(
roles.delete_on + INTERVAL '1 day',
'9999-12-31'
)
)::DATE,
CONVERT_TZ(roles.created_at, 'UTC', 'CET')::DATE
)
) 
+ CASE
-- check if dates are the same, to not add fractional year
WHEN (
EXTRACT(MONTH FROM LEAST(
DATE('#{date.strftime("%Y-%m-%d")}'),
COALESCE( …
```
> Improve calculation membership years (#835)

- app/jobs/invoices/abacus/create_yearly_invoices_job.rb
- lib/hitobito_sac_cas/wagon.rb
- spec/jobs/invoices/abacus/create_yearly_invoices_job_spec.rb
> INVOICE: Yearly invoices job

- app/jobs/invoices/abacus/create_yearly_invoices_job.rb
- spec/jobs/invoices/abacus/create_yearly_invoices_job_spec.rb
Ref: #803 
Previously members with an SacMembership invoice from 2024 and another invoice would also get selected.
> INVOICE: Fix active_members query

- app/domain/invoices/sac_memberships/member.rb
In run  https://github.com/hitobito/hitobito_sac_cas/actions/runs/11048637113/job/30692422707?pr=1034
we see that the abacus spec fails because the github CI somehow manages to get the family members back in a different order (i assume different locales / collections in the database). This should fix the reoccurence of this flaky spec.
> fix flaky abacus spec: order of family members

- app/mailers/event/participation_canceled_mailer.rb
- app/models/sac_cas/event/participation.rb
- db/seeds/custom_contents.rb
- db/seeds/development/events.rb
- db/seeds/development/support/sac_event_seeder.rb
- spec/mailers/event/participation_canceled_mailer_spec.rb
- spec/models/event/participation_spec.rb
> Send email when course participation is canceled

- app/models/external_invoice/course.rb
- spec/controllers/event/participations_controller_spec.rb
> Prevent `ExternalInvoice::Course` from enqueuing the same invoice multiple times

- app/domain/render_markdown_tables.rb
- app/models/sac_cas/custom_content.rb
- app/views/layouts/_mailer_head_sac.html.haml
- lib/hitobito_sac_cas/wagon.rb
- spec/models/custom_content_spec.rb
Fixes #1119
der regex matched `<br>`, weil die newlines im ui zu html converted werden
> Render markdown tables in CustomContent

- app/helpers/sac_cas/standard_form_builder.rb
Fixes #1090
das wurde nur für family fields benutzt und braucht es jetzt nicht mehr
> Use same label for optional and required fields in StandardFormBuilder

- app/models/memberships/common_api.rb
fixes #1161
The primary group gets updated already in after_save/after_destroy
callbacks on Role, so we don't have to do it explicitely in the
membership mutations.
The previous implementation with `update!` naively assumed that the
updated people are valid, which is not necessarily the case so the user
got http 500 error responses.
For the membership mutation we should not care about person validity
unless it is a precondition for the mutation, then we should handle it
explicitely and should not try to update the primary group anyway.
> Do not update primary group explicitely in membership mutations

- app/views/wizards/steps/leave_zusatzsektion/_summary.html.haml
- app/views/wizards/steps/termination/_summary.html.haml
- spec/features/memberships/sac_terminate_membership_wizard_spec.rb
- spec/models/memberships/terminate_sac_membership_spec.rb
CI run with core branch: https://github.com/hitobito/hitobito_sac_cas/actions/runs/11251330640
> Use stimulus controller for dependent checkboxes and add specs

- app/domain/sac_imports/people/person_entry.rb
- app/domain/sac_imports/people_importer.rb
- spec/domain/sac_imports/people_importer_spec.rb
Seit der Personenimport parallelisiert wurde, gibt es race conditions da wir im file mehrere Einträge haben mit gleicher 
* Email Adresse (Person mehrfach registriert)
* navision_id (Person war Mitglied von verschiedenen Familien)
Ausserdem wurden bei mehrfacher Ausführung des imports die Email Duplikate auch mehrfach als AdditionalEmail angelegt.
Des weiteren wurde ein case sensitive where verwendet beim lookup ob eine Email bereits von einer anderen Person verwendet wurde. Devise selber macht aber einen case insensitive search und markiert den record als invalid
> PeopleImporter: fix race condition, do not create duplicate additional_email

- app/controllers/people/external_invoices_controller.rb
- app/views/people/external_invoices/_table.html.haml
This fixes all sortable colums besides the title, the problem is that our Searchable module is based on database sorting (ORDER BY), the sort_expression we get can't be used easily for title sorting, because title is a ruby Method that builds together the title.
Example for Membership Invoices
```
def title
I18n.t("invoices.sac_memberships.title", year: year)
end
```
First solution would be to not enable sorting in the table attrs for titles, if the invoices really have to be sortable by title, we have to consider adding the title as a database attribute, PostgreSQL offers generated columns, but we can only use other entity information in the expression, not I18n translations.
> Use sort_expression to reorder external invoices

- app/jobs/export/backup_mitglieder_export_job.rb
For some reason `@errors` is nil if assigned its original value in initialize
Refs: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/70533/
> Fix backup mitglieder export error handling

- app/views/event/participation_contact_datas/_fields.html.haml
- spec/views/event/participation_contact_datas/_fields.html.haml_spec.rb
Lokal muss zum testen `acceptance_needed?` angepasst werden, damit diese Methode immer true zurück gibt, oder es muss eine Datenschutzerklärung in der Gruppe hochgeladen werden.
> Reintroduce privacy_policy_acceptance_field

- app/views/people/_details_youth.html.haml
- app/views/people/_fields_youth.html.haml
Ref: #1346 
<details>
<summary>Profile View</summary>
</details>
<details>
<summary>Edit View</summary>
</details>
> Override people/_fields_youth to remove AHV number field

- app/domain/sac_imports/csv_source.rb
- app/domain/sac_imports/csv_source/nav1.rb
- app/domain/sac_imports/people/person_entry.rb
- spec/domain/sac_imports/csv_source/nav1_spec.rb
- spec/domain/sac_imports/people/person_entry_spec.rb
* neues NAV1 file wird 3 Spalten mehr haben mit Telefonnummern (am Ende angehängt, die Spalten davor bleiben gleich)
* Importer kann mit altem und neuen file umgehen
Zitat Stefan
> Folgende 3 Spalten werden am Ende der Datei neu hinzugefügt (in genau dieser Reihenfolge):
> 
> -- Privat
> -- Mobil
> -- Geschäftlich
> 
> Bestehende Telefonnummer (Spalte #13) soll neu als Haupt-Telefon geladen werden.
> SacImports: NAV1 import additional phone numbers (HIT-58)

- app/domain/sac_imports/chimp_importer.rb
- app/domain/sac_imports/csv_source.rb
- app/domain/sac_imports/csv_source/chimp.rb
- lib/tasks/sac_imports.rake
import subscribers from all chimp files
* try to find person by email, add subscription (list is opt-in, just blindly create sub if not exists yet without any further logic)
* if not found, log to report
@amaierhofer hier die Resultate meines Import Laufs:
```plain
Chimp 1 (Newsletter) has 51382 lines
Chimp 2 (SAC Inside) has 3039 lines
Chimp 3 (Tourenleiter) has 3566 lines
Type                     |Before|After|Delta
--------------------------------------------
Newsletter Subscribers   |     0|39040|39040
SAC Inside Subscribers   |     0| 1416| 1416
Tourenleiter Subscribers |     0| 3533| 3533
--------------------------------------------
```
* für Newsletter wurden für ~80% der subscriber die Person gefunden
* für SAC Inside für ~50%
* für Tourenleiter fast alle
z.T. melden sich die …
> SacImports: implement chimp importer (HIT-633)

- app/domain/sac_imports/csv_source/wso2.rb
- app/domain/sac_imports/wso2/person_entry.rb
- app/domain/sac_imports/wso2_people_importer.rb
- spec/domain/sac_imports/wso2/person_entry_spec.rb
@amaierhofer der wso2 import soll ein zusätzliches log file schreiben mit dem mapping von wso2 uuid -> hitobito id.
Das ist so mit agu abgesprochen.
output: 
```plain
hitobito_id;um_user_name
123456;000064d4-d3d6-4376-a4d5-075b85123456
```
(Dabei habe ich noch entdeckt, dass das label für die Telefonnummer nicht dem vordefinierten label entspricht -> angepasst)
> SacImports: WSO2 log uuid -> hitobito id mapping

- app/controllers/sac_cas/groups/self_registration_controller.rb
- app/models/wizards/signup/abo_basic_login_wizard.rb
- app/models/wizards/signup/abo_magazin_wizard.rb
- app/models/wizards/signup/abo_touren_portal_wizard.rb
- app/models/wizards/signup/sektion_wizard.rb
- app/views/groups/self_registration/_aside_abo.html.haml
- app/views/wizards/steps/signup/abo_magazin/_person_info_table.html.haml
- lib/hitobito_sac_cas/wagon.rb
- spec/features/signup/abo_basic_login_spec.rb
- spec/features/signup/abo_magazin_spec.rb
- spec/features/signup/abo_touren_portal_spec.rb
- spec/models/wizards/signup/abo_basic_login_wizard_spec.rb
- spec/models/wizards/signup/abo_magazin_wizard_spec.rb
- spec/models/wizards/signup/abo_touren_portal_wizard_spec.rb
fixes: #1404, #1425, #1423, #1421
https://github.com/hitobito/hitobito_sac_cas/actions/runs/12397257781
> Do not include main email step when logged in and build as current_user

- app/controllers/sac_cas/event/participations_controller.rb
- spec/controllers/event/participations_controller_spec.rb
Gibt es einen Grund nicht ein `after_update` auf dem Participation Model zu verwenden, ähnlich zu den Event States? Aktuell implementieren wir an verschiedenen Orten das verschicken dieser Mails, gibt es einen bestimmten Grund dafür, weil der Status wird immer auf `:summon` gesetzt. Ich finde auf die Schnelle auch keine anderen Orte wo wir den Status auf `:summon` setzen und keine Email verschickt werden sollte.
Das gleiche Problem/Frage kam auch bei https://github.com/hitobito/hitobito_sac_cas/issues/1389 auf... wo wir die Anmeldebestätigungs-Mail mal über den Controller, ein anderes mal beim assignen über Application Market verschicken, obwohl beide Actions den Status der Participation einfach auf "Bestätigt" setzen. Auch dort bin ich mir jedoch nicht sicher ob es weitere Orte gibt, bei …
> Feature/1455/summon email when maunually summoning (#1455)

- app/models/wizards/memberships/terminate_sac_membership_wizard.rb
- spec/models/wizards/memberships/terminate_sac_membership_wizard_spec.rb
- spec/views/wizards/steps/_termination_choose_date.html.haml_spec.rb
Sentry Issue: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74127 und https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74126
To recreate Problem, terminate a stammsektion role with
(any stammsektion role).update_column(:terminated, true)
Then just click Mitgliedschaft anpassen and SAC Mitgliedschaft beenden, choose "now" and finish the wizard steps, it will throw an error and not send the email without the fix
> Fix email not knowing old section when terminating now

- app/controllers/sac_cas/event/participations/mail_dispatches_controller.rb
- app/helpers/sac_cas/dropdown/event/participation/mail_dispatch.rb
- app/models/sac_cas/event/participation.rb
- lib/hitobito_sac_cas/wagon.rb
- spec/controllers/event/participations/mail_dispatches_controller_spec.rb
- spec/helpers/dropdown/event/participation/mail_dispatch_spec.rb
https://github.com/hitobito/hitobito_sac_cas/actions/runs/13174205967
Aktuell werden die Emails noch nicht in der Sprache der jeweiligen Persone verschickt, alle Mailer schauen aktuell auf die Kurssprache, ich möchte noch abklären ob nur beim manuellen Versand die Sprache der Person benutzt werden soll, oder am besten bei jedem Mailer automatisch
> Add various emails to send out manually to participants (#1571)

- app/jobs/export/backup_mitglieder_schedule_job.rb
As we reference this class in the wagon file and it is referenced
before the model mixins are inserted, this results on misconfigured
Sektion and Ortsgruppe models
> Favour string over constants if code is loaded initialization

- app/models/wizards/signup/abo_magazin_wizard.rb
- spec/models/wizards/signup/abo_magazin_wizard_spec.rb
Users should be able to subscribe to different abos, with the current implementation this is not possible.
> Check for group in member_or_applied? for abo magazin signup

- app/views/devise/sessions/_helpful_links.html.haml
- app/views/public_events/show.html.haml
- config/locales/wagon.de.yml
- db/migrate/20250709160605_set_main_self_registration_group.rb
- spec/fixtures/groups.yml
- spec/views/devise/sessions/new.html.haml_spec.rb
- spec/views/public_events/show.html.haml_spec.rb
Specs sind eigentlich in ordnung, sieht aber so aus als ob das automatische Branch wechseln weg vom  `sac-master` nicht funktioniert https://github.com/hitobito/hitobito_sac_cas/actions/runs/16219245706/job/45795578338?pr=1914#step:3:66
> Consolidate links on login pages (#1908)

- spec/models/memberships/join_zusatzsektion_spec.rb
This is specifically necessary since we only have a membership_configs fixture for 2024. So if at some point we would test outside of that year we would have issues when calculating abacus invoice amounts
> Use travel_to for spec to use consistent timeframe
